### ISSUE TITLE
koa and deno/oak?

### ISSUE THREAD

**Issue by chovy** [kartikk221/hyper-express#1]
How does it compare to koa/node and deno/oak?

**Comment by kartikk221** [comment]
I'm not sure about Deno as I personally do not use Deno and HyperExpress is meant to be Node.js focused but HyperExpress should be much faster than Koa as Fastify is faster than Koa in their benchmarks and If you look at the benchmarks in the README, HyperExpress beats Fastify by a huge margin in high stress environments. You can look at Fastify's benchmarks here: https://www.fastify.io/benchmarks/

**Comment by kartikk221** [comment]
You could also look at https://web-frameworks-benchmark.netlify.app/result for benchmarks across various programming languages/frameworks. NanoExpress would be closest in performance to HyperExpress as both are built atop uWebsockets.js
