### ISSUE TITLE
'App construction failed' when certificates set

### ISSUE THREAD

**Issue by benoitlahoz** [kartikk221/hyper-express#111]
Hello and thank you for HyperExpress. 

I have a strange issue : 

Server creation is ok when **I do not** pass certificates paths, but crashes with this message `App construction failed` when I fill `key_file_name` and `cert_file_name` options. 

I checked: the file paths are valid and point to certificate and key **generated with mkcert**

Thank you!

Version: 5.9.2
Node: 16.13.0

**Comment by benoitlahoz** [comment]
I'm very sorry: this was just a typo in one of my path. 

But, I admit that I would have loved to have a more explanatory error :-) 

Thank you very much for the work!

**Comment by kartikk221** [comment]
Hey @benoitlahoz Good idea, will try and throw a more informative error for this exception. Thanks!
