### ISSUE TITLE
Global middlewares don't execute on some routes under certain conditions

### ISSUE THREAD

**Issue by BobbyWibowo** [kartikk221/hyper-express#118]
For routes that have `options` configured BUT have no local middlewares, for example:
```js
// any(String: pattern, Object: options, Function: handler)
server.get('/', { max_body_length: 100 * 1e6 }, (request, response) => { response.status(200).end() })
// any(String: pattern, Function | Function[]: ...middleware, Function: handler), but empty middleware array
server.get('/', { max_body_length: 100 * 1e6 }, [], (request, response) => { response.status(200).end() })
```
They will not have global middlewares executed before their handler functions

On the other hand, if they have (array of) local middleware(s), OR empty `middleware` array in `options`, they will work:
```js
// any(String: pattern, Function | Function[]: ...middleware, Function: handler)
server.get('/', { max_body_length: 100 * 1e6, middlewares: [] }, (request, response) => { response.status(200).end() })
// any(String: pattern, Object: options, Function | Function[]: ...middleware, Function: handler)
server.get('/', { max_body_length: 100 * 1e6 }, (_, _, next) => { next() }, (request, response) => { response.status(200).end() })
```

---

Sample test script: https://github.com/BobbyWibowo/hyper-express-playground/blob/master/tests/no_local_middleware.js

Sample server logging:
![image](https://i.fiery.me/S3n3.png)

**Comment by kartikk221** [comment]
This bug has been fixed in the recent v6.4.9 release. Let me know If you still encounter this issue with the new version.
