### ISSUE TITLE
[Question] Duplicate Routes

### ISSUE THREAD

**Issue by Darker-Ink** [kartikk221/hyper-express#123]
Hey, Just wondering is there any reason there can't be duplicate routes?

**Comment by kartikk221** [comment]
uWebsockets.js doesn't play well with duplicate routes and HyperExpress compiles all routes down to uWS native calls. Also, there is no reason one should ever have duplicate routes as it means bad code design or unused code both of which can spiral into bugs or unintended behavior from your application.
