### ISSUE TITLE
Route handlers lose type when middleware is defined inline

### ISSUE THREAD

**Issue by Mahamed-Belkheir** [kartikk221/hyper-express#126]
Running into a weird problem where the `UserRouteHandler` type is lost if you use middlewares with the route handler e.g:

```ts
import { Router } from "hyper-express";

let router = new Router();

router.get('/hello', (req, res) => {
  // req and res types are inferred fine
})


router.get('/hello', (_1, _2, next) => { next() }, (req, res) => {
  // middleware param types are fine, but the final handler has implicit anys for req and res
})
```
req and res are of type any, while the middleware function type is inferred correctly, I peeked at the type definition for router[method] functions and they're correctly typed, so not sure why this is happening 🤔

reproduced [here](https://replit.com/@MahamedBelkeir/hyper-express-middleware-type-issue)

**Comment by kartikk221** [comment]
Hey, this bug has been fixed in the recent v6.4.11 release. It seemed to have to do with the MiddlewareHandler being spread inside of the original spread syntax.
