### ISSUE TITLE
Type-safe routing, overriding Router declared type methods

### ISSUE THREAD

**Issue by Tyrenn** [kartikk221/hyper-express#131]
Hi everyone, thanks for this promising package ! 
I'm trying to implement it within a backend application using typescript. Hoping to reach better performance.

### Describe the problem

However, I'm still struggling with writting type-safe routes using typescript.

I wan't to ensure not using an incompatible UserRouteHandler for a specific route. In other words I'm trying to redefine Router methods so they propose generic types and narrow the type of UserRouteHandler that we can use.
For example, the post method I'm trying to redefine is something like this:

```ts
post<T extends {Body? : any, Response : any}>( pattern : string, ..handlers : ...((request : Request<T['Body']>, response : Response<T['Response']>) => any)[]): void
```
Such post method would allow me to narrow the UserRouteHandler type and avoid mistakes.

So I tried to "Augment" Router type and also write a proxy class but none of it works.
* Overriding class delcaration : It seems that we can't completely override a declared class so I can't really change the method signature of the Router class type.
* Class inheritance : using typescript we can't manage to define signatures matching the ones in the type Router declaration files. The ...rest parameter is not working.
* Class proxy : really ugly and loosing autocompletion / some signature possibilities.

### Describe the proposed solution

I'm thinking of 3 solutions:

* Implement a type-safe mecanism based on type generics directly in d.ts files. However, this would impose a type safe mecanism and move away from the basic express JS mecanism.
* Change the type declaration of the router from class to interface. If I understand correctly, overriding interfaces type declaration is easier as we can change names and add properties.
* Explain to me how I can get by otherwise, after several hours on this problem, I can't find a satisfiying solution...

### Alternatives considered

For now I'm going for the Class proxy solution.
Another solution is to create a sort of UserRouteHandler wrapper which takes Types but again, kind a ugly.

### Importance
Would be nice to have

Thanks again for this package

**Comment by kartikk221** [comment]
Hello, I am having trouble following what you are proposing specific to the `UserRouteHandler` because it is a very simple callback type which defines the Request, Response and return type as any matching HyperExpress's behavior for the callbacks.

Are you proposing a way to be able to specify fine-tuned types per route for things such as Body, Request and Response locals?

**Comment by Tyrenn** [comment]
Hello,

Sure, i'll try to be more precise.

I want to find a way to narrow the UserRouteHandler type that can be used inside route definitions. In particular, in my case, I'm trying to specify a more precise type for `path_parameters`, `body` and Response payload (what would return an `UserRouteHandler`).

For that, I need first to redeclare some types, especially `Request` and `UserRouteHandler`.

```ts
const type MyRequest<T extends {Body? : any, Params? : string} = {}> extends Request<any>{
	body: T['Body'];
	path_parameters : T['Params'] extends string ? 
		{[key in T['Params'] as key extends string ? key : never] : string} : never;
}
const type MyUserRouteHandler<T extends {Body? : any, Params? : string, Response : any}> = 
	(request : MyRequest<T>, response : Response) => T['Response'] | Promise<T['Response']>
```

This way I can write type safe UserRouteHandler and know which type is the `body` and `path_parameters`. But in order for the whole Route to be type safe I need route definition method implementing those types as generics. Something like :

```ts
	// New Router signature wanted
	get<T extends {Params?: string, Response : any}>(
		pattern : string, 
		...handlers : [MiddlewareHandler | MiddlewareHandler[], MyUserRouteHandler<T>]
		);
```

Such new signature will prevent errors and allow to define type safe routes :

```ts
	const handlerinstance = async (request : MyRequest, response : Response){
		return "Hello";
	};

	router.get<{Response : number}>('/error', handlerinstance) // Type error raised !

	router.get<{Response : string}>('/working', handlerinstance) // Valid
```

So I tried to achieve this by redeclaring `Router` class type, augment it with new signatures for each methods with generics. BUT as the declared type is a class type I can't manage to do it. Either I get Typescript warnings about my new signature not compliant with already declared signature or I loose the ability to pass infinite number of Middlerwares.

```ts
// Me trying to mess with type overriding...
declare module "hyper-express" {

	class NewRouter extends Router{
		get<T extends {Params?: string, Response : any}>(pattern: string, handler: MyUserHandler<T>): void;
		get<T extends {Params?: string, Response : any}>(pattern: string, ...handlers: [...MiddlewareHandler[], MyUserHandler<T>]): void;
		get<T extends {Params?: string, Response : any}>(pattern: string, routeOptions : UserRouteOptions, ...handlers: [...MiddlewareHandler[], MyUserHandler<T> ]): void;
	}
}
```

Another thing I tried is to write a class Proxy but it ends up using an ugly any to match all types of signature.

As far as I understand it, we can't really redeclare correctly a class type in typescript. Only interface types are "augmentable". Noting that the actual typescript signature in `router.d.ts` could have not been achieve using real Typescript classes as the rest parameters doesn't work with signature overload.

What would I desire is to be able to redefine Router types. The best way I can think of would be to change te ```class Router``` in the declaration file for an interface like this :

```ts
// Router.d.ts
export interface Router {
    new() : void;
	 
	get(pattern: string, handler: UserRouteHandler): void;
   get(pattern: string, ...handlers: [MiddlewareHandler | MiddlewareHandler[], UserRouteHandler]): void;
   get(
		pattern: string,
		options: UserRouteOptions,
		...handlers: [MiddlewareHandler | MiddlewareHandler[], UserRouteHandler]
	): void;
	
	 //... All other methods
```

This way, I believe I would be able to redefine Router interface more easily. However, I'm not sure if Typescript would correctly bind the Router class to the interface... I'm planning to try it by the end of the week. If it doesn't, then I'm open to any insights or ideas to "correctly" achieve type safe routes.

I hope my problem is clearer !

Cheers :)

**Comment by kartikk221** [comment]
I'm not too experienced with TypeScript, so wouldn't know of very niche tricks to get this to work. What if you could provide a type to each route when calling it which would be a generic?

Something like

```
server.get<CustomGenericType>("/login", (request, response) => {});
```

**Comment by Tyrenn** [comment]
Hello, back with tests and answers.

I first tried to declare an interface only in `router.d.ts` file instead of a class. It doesn't work as it prevent from using the constructor. It requires the dev to redeclare a class type on its own using :

```ts
export Router implements Router{}
```

But if this line is declared in the `router.d.ts`, our problem of "Augmenting" the Router stays the same, Router class exists and "Augmenting it" is not possible. I also tried with an inteface with `new : () => void` but it's still not recognized as a real object that you can initiate with new.

So redeclaring a class is not an option. It leaves us with either redeclare a wrapper class around router.

> If you figure something out by modifying the original types, feel free to make a Pull Request.

I'll sure try to find an elegant proposal for this kind of safe route to be possible.

In the meantime, I've found a working solution with a wrapping class. Kind of wierd as it avoid type checking by using the prototype. But at least, signatures are all good and customizable without losing the rest parameter :

```ts
import {Router as HyperExpressRouter} from 'hyper-express'

export class Router{
	router : HyperExpressRouter;

	constructor(){
		this.router = new HyperExpressRouter();
	}
	
	get<T extends {Params?: string, Response : any}>(pattern: string, ...handlers:  [...MiddlewareHandler<T>[], MyUserHandler<T>]): void;
	get<T extends {Params?: string, Response : any}>(pattern: string, options : UserRouteOptions, ...handlers:  [...MiddlewareHandler<T>[], MyUserHandler<T>]): void;
	get<T extends {Params?: string, Response : any}>(
		pattern: string, 
		...handlers: [UserRouteOptions | MiddlewareHandler<T>, ...MiddlewareHandler<T>[], MyUserHandler<T>] | [...MiddlewareHandler<T>[],  MyUserHandler<T>]): void{
		Object.getPrototypeOf(this.router).get.call(this.router, pattern, ...handlers);
	}

	...

```

That's all for now, thanks.
