### ISSUE TITLE
Get Request Body

### ISSUE THREAD

**Issue by Darker-Ink** [kartikk221/hyper-express#133]
Hey, I'm looking to see if its by chance possible to get the Body of a post request ETC.

I've tried just doing `req.body` and got nothing then tried the `body-parser` NPM package but it didn't work. It would just never solve the requests so I was wondering if theres a way to get the body currently..

**Comment by kartikk221** [comment]
Hello, we currently provide multiple methods to parse the incoming body of the request. At the moment, there isn't full compatibility with some low level Node APIs hence the `body-parser` package will likely not work at the moment. You can write your own middleware to automatically parse the body and populate the `req.body` property or manually retrieve the body from incoming requests.
