### ISSUE TITLE
next() equivalent for async middleware?

### ISSUE THREAD

**Issue by adonespitogo** [kartikk221/hyper-express#140]
Hi, what is the right way to skip/passthrough the request to the next middleware in an `async` middleware?

For example:

```js
app.use(async (req, res) => {
  // I wanted to call next() here
})
```

**Comment by kartikk221** [comment]
As stated in https://github.com/kartikk221/hyper-express/blob/master/docs/Middlewares.md you can have two types of middlewares. Synchornous middlewares and asynchronous middlewares. The example you posted above is an asynchronous middleware and for asynchronous middlewares you do NOT need to call next() as the request will continue once your middleware async resolves. So for example:
```js
app.use(async (req, res) => {
  // This will happen first
  await some_operation_1(req);

  // This will happen second
  await some_operation_2(req);

  // Since you have no more code below and this callback resolves, HyperExpress will automatically continue to the next middleware/handler
})
```
