### ISSUE TITLE
Error with cors

### ISSUE THREAD

**Issue by mlaina** [kartikk221/hyper-express#142]
Hello! I have problems when making calls from a browser, it returns net::ERR_EMPTY_RESPONSE. I have tried to allow access with the "cors" library just like in express.

```
const cors = require("cors");
const app = new HyperExpress.Server();
app.use(cors());
```

However it doesn't work as I expected.
Please, could you help me?

**Comment by kartikk221** [comment]
net:ERR_EMPTY_RESPONSE usually means the server sent a response but it had no content.
I would take the following steps to determine what the problem may be:
1. Create a not found handler to log and send as Not Found response with `server.set_not_found_handler()`
2. Create a error handler to log potential errors with `server.set_error_handler()`

Also, do you have any routes that you actually serve some content from? If I am not mistaken, the `cors()` middleware simply adds headers which means it won't send a `Response` hence if you do not have any routes created that you are visiting then `HyperExpress` will simply not respond with anything.
