### ISSUE TITLE
support for res.statusMessage ?

### ISSUE THREAD

**Issue by desplmfao** [kartikk221/hyper-express#143]

**Comment by kartikk221** [comment]
Hello, could provide some examples of how this property would work and where it is already in production? Do you want a getter/setter for the statusMessage?

**Comment by desplmfao** [comment]
to make it possible to set custom status messages like 

HTTP/1.1 507 User doesn't have enough storage

**Comment by kartikk221** [comment]
Support for `Response.statusMessage` has been added in the recent v6.5.3 update.
