### ISSUE TITLE
Generic type 'WebSocket<UserData>' requires 1 type argument

### ISSUE THREAD

**Issue by Hookyns** [kartikk221/hyper-express#146]
Hello,

I've just installed hyper-express so I can test it, but I get TS error:

```
node_modules/hyper-express/types/components/ws/Websocket.d.ts:114:16 - error TS2314: Generic type 'WebSocket<UserData>' requires 1 type argument(s).

114     get raw(): uWebsockets.WebSocket;
                   ~~~~~~~~~~~~~~~~~~~~~
```

It's just a typing issue. `uWebsockets.WebSocket` has one type argument declared and it is required. 
I'll create a PR draft with the fix.

**Comment by kartikk221** [comment]
Good catch, I'll merge the PR once it is out of draft. Thanks!
