### ISSUE TITLE
how can use ejs with hyper-express

### ISSUE THREAD

**Issue by johnnguyen-nodejs** [kartikk221/hyper-express#155]
please show me how can i connect ejs tample with hyper-express server, thank sir

**Comment by kartikk221** [comment]
Hi, feel free to make a discussion for this but you can utilize something like `live-directory` to first load your EJS template files into memory and then you can render them into templates using the `ejs.compile()` function and then rendering using `ejs.render()`. Once you have gotten the basics working, you can likely create a middleware which injects these methods onto the Request itself if you desire.
