### ISSUE TITLE
Using Hyper-Express in a Deno runtime

### ISSUE THREAD

**Issue by pxCaptcha** [kartikk221/hyper-express#161]
Hello everyone.

I'm aware of that this was build with a focus on NodeJS. I wanted to ask if theres any way to get this project to run within Deno it self, as I think this would bring even better results than in JS. 
Deno has a problem handling the .node files coming with this project, as Deno doesnt support handling for .node files.

Is there any way around this issue? 

Thanks!:)

**Comment by kartikk221** [comment]
Hyper-Express running in Deno almost entirely depends on uWebsockets.js being compatible with Deno. The maintaining of uWebsockets.js does not seem to support every version of Node.js, so I would doubt he would have gone out of his way to potentially support Deno. With that said, If Deno has enough compatibility with Node.js's native addons then you may have some luck but highly unlikely something can be figured out as you mentioned Deno does not support .node files which is what uWebsockets is compiled as to work with Node.js as an addon.

I would recommend you potentially follow up in https://github.com/uNetworking/uWebSockets.js as If you can have the maintainer add support for Deno, then Hyper-Express and any uWebsockets.js dependent webservers automatically become compatible.
