### ISSUE TITLE
Typo in examples. 

### ISSUE THREAD

**Issue by reedHam** [kartikk221/hyper-express#164]
Hi, thanks for your hard work. 

When I was going over the docs I found some strange wording. 

https://github.com/kartikk221/hyper-express/blob/4d427cbd7b8bb7dfe158cb702330e399a6b9e4a1/docs/Examples.md?plain=1#L37

Also kind of confused about what is going on with the atomic response and how that could improve performance.

I'm excited to try using this webserver that actually seems to care about performance!

**Comment by kartikk221** [comment]
Hey, nice catch. Feel free to make a PR and I'll merge it for any typos.

From what the uWebsockets.js developer has mentioned about .atomic() which under the hood does a .cork() its intended use is to essentially use it when you are doing a lot of network calls in a single go but tbh I haven't really experienced any significant speed-up when using it or building it into the Response.send() handler which already makes a bunch of network calls in a single execution.

If you find out what it is supposed to help with, let me know and I'll be glad to implement changes. In regards to performance, yeah HyperExpress is pretty much the fastest webserver you'll find in the whole Node.js ecosystem that offers an Express-like experience.

You can see https://web-frameworks-benchmark.netlify.app/result?l=javascript for up to date benchmarks.
