### ISSUE TITLE
Router OPTIONS request CORS rejection

### ISSUE THREAD

**Issue by gutentag2012** [kartikk221/hyper-express#165]
Hello there, I just found a possible bug, where by default all OPTIONS requests to a route created by a router reject the preflight request with a CORS error, even with having a CORS middleware enabled.

```
import { Server, Router } from 'hyper-express'
import cors from 'cors'

const app = new Server()

app.use(cors())

app.use((req, res, next) => {
  console.log('auth', req.headers['Authorization'])
  next()
})

const router = new Router()

router.get('/', (req, res) => {
  res.json([{ name: 'test' }])
})

app.use('/applications', router)

const port = parseInt(process.env.PORT ?? '3333')
app
  .listen(port)
  .then(() => console.log(`Started application on port ${port}`))
  .catch((err) => console.log(`Error while starting server "${err.message}"`))
```

Using this app code a request sent through fetch or axios from e.g. a React app, will fail. If `app.options("/applications", () => {})` is added to the code, the same request will go through and not fail.

Funny enough, if I send a request through an http client or even the browser, the request works without this line.
I am not to sure about this, but maybe that is because my http client and the browser do not sent preflight requests to the OPTIONS enpoint.

**Comment by kartikk221** [comment]
Some middlewares don't properly work with HyperExpress. You can achieve CORS my creating your own middleware which intercepts requests, checks for OPTIONS method, and then writes CORS headers and sends response.
