### ISSUE TITLE
 Enhance type checking for router handlers to prevent server hangs due to incorrect return types

### ISSUE THREAD

**Issue by reedHam** [kartikk221/hyper-express#167]
Hi,

I've thoroughly enjoyed using the HyperExpress framework so far!

However, I recently encountered an issue where I inadvertently returned an object instead of a JSON response, which caused my server to hang on that particular request. Here's a snippet of the problematic code:

```typescript
router.post("/", async (request, response) => {
    const reqJson = await request.json();
    if (!reqJson.id) {
        return {
            "message": "request missing ID" 
        }
    }
    return response.status(201).json({
        "message": "created"
    });
});
```

While I acknowledge this was entirely my error, I'd like to propose enhancing the type checking for router handlers to help users avoid similar pitfalls and improve the overall developer experience.

Currently, the return type for router handlers is `any`:
https://github.com/kartikk221/hyper-express/blob/4d427cbd7b8bb7dfe158cb702330e399a6b9e4a1/types/components/router/Router.d.ts#L8

From what I've gathered in the documentation and the [handle function](https://github.com/kartikk221/hyper-express/blob/4d427cbd7b8bb7dfe158cb702330e399a6b9e4a1/src/components/router/Route.js#L63), the result returned from the router handlers appears to be inconsequential (though my assumption may be incorrect).

I recommend implementing stricter type checking for the return type of router handlers, as this could prevent users from making similar mistakes in the future.

If you agree with my suggestion, I'd be more than willing to contribute by creating a PR to address this issue. Please let me know if you have any questions or if I may have overlooked a more suitable solution. Thank you for your excellent work on HyperExpress!

**Comment by kartikk221** [comment]
Hey, so the reason why I put the any type for the return type was that the handle function's return output is inconsequential for route handlers. The only time the output of a handler is consequential is for middlewares. I see what caused the issue in your case and expecting a void or never return type may be smart to prevent errors, however, it would be a bit inaccurate to the functional aspect in that the return value is inconsequential for a route handler.

This is definitely a change that should be considered for a major upgrade version but making it in a minor version may lead to type failures for existing projects which use HyperExpress while the function of the framework will not have changed.

With that said, I do plan on re-building HyperExpress in TypeScript this summer and will def keep strong type safety in mind during the rebuild for scenarios like these and the major changes will close the gaps between Express.js and HyperExpress and also improve the experience overall.

**Comment by TimiBolu** [comment]
I will like to volunteer for the task of rebuilding hyper express in typescript in case you need any help. I haven't much understanding of the codebase and the concepts but I am willing to learn and I have experience with TypeScript.
