### ISSUE TITLE
Websocket's context has bad types

### ISSUE THREAD

**Issue by OmgImAlexis** [kartikk221/hyper-express#168]
Currently `WebsocketContext` is typed as the following with no easy way to extend it.

```ts
export type WebsocketContext = {
    [key: string]: string
}
```

Upgrade should also be passed the same context type.

```ts
upgrade(context?: Object): void;
```

Also for what it's worth `Record<string, unknown>` should be used if you want a plain object not `Object` as that's the `Object` constructor. https://stackoverflow.com/questions/49464634/difference-between-object-and-object-in-typescript

**Comment by OmgImAlexis** [comment]
Actually I'm a bit confused. There's also `TUserData` which is passed to `Websocket` which also seems to be the websocket context? 🤔

**Comment by kartikk221** [comment]
Hey, I believe the original `WebsocketContext` was something I implemented and then later on somebody made a PR with the `TUserData` type which was supposedly more accurate. I'm gonna assume both are not too accurate hence I would be more than willing to merge a `Record<string, unknown>` PR which does seem to be the best option at the moment for type accuracy.

**Comment by OmgImAlexis** [comment]
I played around with this and get it working, would you be okay with me opening a new PR with the types resolved?
Seems `TUserData` should actually be the context, context also needs to be passed around in a few places.

In my code I can now do something like this and it's fully typed, I feel we could remove `TUserData` in replace we'll use context so this would only need a single generic not the two like my example shows.

```ts
type WebsocketContext = { this_is_typed: boolean;  }
webServer.ws<unknown, WebsocketContext>('/websocket', ws => {
  if (ws.context.this_is_typed) {}
});

**Comment by OmgImAlexis** [comment]
Pulling in @Hookyns who write the other PR to get their take.

**Comment by kartikk221** [comment]
> I played around with this and got it working, would you be okay with me opening a new PR with the types resolved?
For sure, yeah feel free to open a new PR for type improvements.

**Comment by kartikk221** [comment]
Hey @OmgImAlexis Just to push things forward, If no response from @Hookyns is received by Monday, we should be good to move forward with your solution. Currently the goal should be to fix things without making any breaking changes. Ideally, the type system has to be redone better in the next major version increment which would be coming this summer.

**Comment by OmgImAlexis** [comment]
Sounds good to me.

**Comment by Hookyns** [comment]
Sorry, I missed notification.

Sounds good. 👍

**Comment by OmgImAlexis** [comment]
Okay Ill get the PR opened up as soon as I have a moment.

**Comment by kartikk221** [comment]
Hey, I'll be closing this issue for now since a solution has been found and your PR is expected in the future. Feel free to re-open if something comes up.
