### ISSUE TITLE
Can't handle backpressure correctly with response.write

### ISSUE THREAD

**Issue by snowbldr** [kartikk221/hyper-express#17]
Response.write should return a boolean so backpressure can be handled in a Writable correctly.

**Comment by kartikk221** [comment]
Response.write() usage is already implemented in 5.1.2 for streaming and the total_size parameter is now optional. No need to use a Writable as the stream method directly consumes data from the Readable stream and pauses/resumes as uWebsockets allows for more chunks to be served with backpressure handling. You can look at source in src/components/Response.js for how stream method works under the hood.

**Comment by snowbldr** [comment]
I can't use the response in a pipeline without this... 

Also, the express response implements writable, so don't have parity with express until this is implemented.

I guess I'll use a different framework...

**Comment by kartikk221** [comment]
See 5.2.0 for the new changes in which Response.write() now returns a Boolean similar to Response.send() and other write based methods. Also, Response.drain() has been implemented to work in conjunction with Response.write() when implementing your own backpressure strategy. See Examples for a new example that implements Readable to Writable pipe based streaming endpoint.

The goal with hyper-express is not to have 100% parity with express as uWebsockets.js is fundamentally different from express in how it works and handles the request lifetime flow. The reason why Response.write() is not implemented similar to Express.Response.write() is so the user has full flexibility to define how they want to handle backpressure. If you notice, none of the uWebsockets.js methods handle backpressure themselves and thus for consistency with the underlying driver of this package, this behavior is extended to the methods of HyperExpress as well.
