### ISSUE TITLE
response header lowercase

### ISSUE THREAD

**Issue by transtone** [kartikk221/hyper-express#172]
set a header with 
```js
response.header('Access-Control-Allow-Credentials', 'false')
```

the header become lowercase `access-control-allow-credentials`. 
Is there any settings about this?

https://github.com/kartikk221/hyper-express/blob/dff6b090de5fa9e1f48148056e4b080cddf527ba/src/components/http/Response.js#L195

why set this?

**Comment by kartikk221** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers HTTP headers are meant to be case-insensitive hence they are lowercased to prevent incorrect case readings. Why is case-sensitivity important for you in your use case?
