### ISSUE TITLE
Could not proxy react website to hyper-express API

### ISSUE THREAD

**Issue by josejooj** [kartikk221/hyper-express#174]
I'm making a website with `React` and a API in `hyper-express`, but when trying to proxy the react requests to api, i receive this error in react console:
```js
Proxy error: Could not proxy request /api/session from localhost:3000 to http://localhost/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /public/assets/favicon.ico from localhost:3000 to http://localhost/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```
But when i do the same thing, but with `express`, the code runs without error, and making the requests normally... What can i do to run this with hyper-express?

This is my hyper-express API code (typescript)
```ts
import HyperExpress from 'hyper-express';
import { Routes } from './Routes';

const server = new HyperExpress.Server({ fast_abort: true, fast_buffers: true, trust_proxy: true });
const methods: Array<"get" | "use" | "post" | "delete" | "patch"> = ["get", "use", "post", "delete", "patch"];
const port = 80;

for (const route of Routes) {
    for (const method of methods) {
        if (route[method]) {
            if (method == "use") route.pattern ? server.use(route.pattern, route.use!) : server.use(route.use!);
            else server[method](route.pattern, route[method]!)
        }
    }
}

server.listen(port)
    .then(x => console.log(`[API] - I'm online on port ${port}`))
    .catch(e => console.log(`[API] - Error: I can't open on port ${port}`));
```

**Comment by josejooj** [comment]
This is why I think the error is with hyper-express:

## This is network debugger with Express: 
![See image](https://github.com/kartikk221/hyper-express/assets/76636096/c0d73ce3-e53d-416c-8ca3-fa697102efd8)
## This is network debugger with Hyper-Express: 
![image](https://github.com/kartikk221/hyper-express/assets/76636096/44491a9f-9cf5-403d-afc0-6cee1257db79)

OBS: When i try to access the api with Chrome, the api runs whitout problems, the problem is only to work with the proxy
![image](https://github.com/kartikk221/hyper-express/assets/76636096/fc94a0f0-89ac-4097-94ba-2400b000fbe4)

**Comment by kartikk221** [comment]
This seems to be an implementation error in your implementation rather than Hyper-Express. I see that the session requests are sending back an HTTP 500. Check your logs for any errors from hyper-express or your own logic that may be sending the 500 error there? Please analyze the HTTP 500 errors and provide the error traces logged which are causing the HTTP 500 response codes.
