### ISSUE TITLE
MiddlewareHandler type prevents extending Request with extra properties

### ISSUE THREAD

**Issue by denyeo** [kartikk221/hyper-express#176]
Hey there, thanks for the nice framework. I've been trying to write middleware that adds data to the `Request` object (as mentioned in the [Middleware example](https://github.com/kartikk221/hyper-express/blob/master/docs/Examples.md#using-global--routemethod-specific-middlewares)), but the MiddlewareHandler type requires a parameter of type `Request<DefaultRequestLocals>`:

https://github.com/kartikk221/hyper-express/blob/dff6b090de5fa9e1f48148056e4b080cddf527ba/types/components/middleware/MiddlewareHandler.d.ts#L7

This seems to prevent middleware from adding new properties to the Request object without causing a type error:

```js
async hyperExpressMiddleware(request: Request, response: Response, next: MiddlewareNext) {
  request.inertia = ... // TS: Property 'inertia' does not exist on type 'Request<DefaultRequestLocals>'.
```

 If I instead extend the `Request<DefaultRequestLocals>` type with an intersection and supply the extended type as a parameter, then at `app.use(middleware)`, Typescript says "No overload matches this call" (because my extended `Request` type doesn't match MiddlewareHandler's type definition).

In MiddlewareHandler, should `Request<DefaultRequestLocals>` instead be `Request<any>` or something else? Since `Request` is intended to be extensible (e.g. to store context), seems like its type ought to support that.

edit: Sorry, just saw [an old issue about types](https://github.com/kartikk221/hyper-express/issues/82) that you replied to. Seems like making the additional property nullable makes the types work, as you suggested. Guess this solves the issue for both middleware and route handlers.

**Comment by kartikk221** [comment]
Hello, can you try extending DefaultRequestLocals and then setting that as the `Request` generic?

**Comment by denyeo** [comment]
Okay, I've dug into the issue.

The type parameter `DefaultRequestLocals` defines Request.locals, which explains why TS didn't allow me to set my custom property at `request.inertia`. I just assumed I could set custom properties on Request directly (haven't used Express much). I've extended DefaultRequestLocals as you suggested and  `request.locals.inertia` becomes type-accessible.

That said, in order for server.use(middlewareHandler) to match the correct use() overload, the custom property still has to be made nullable: `inertia?`. So that was still the root issue.

Thanks, the issue's resolved!
