### ISSUE TITLE
How can I use pug with hyper-express server?

### ISSUE THREAD

**Issue by nosovandrew** [kartikk221/hyper-express#178]
I want to use pug for writing html pages, but when when I use res.render method, I got error that Hyper Express doesn't support render method.

Addition issue is that I can't set view engine configuration.

**Comment by kartikk221** [comment]
hyper-express doesn't currently support view engines natively meaning you would have to write your own wrapper function to achieve rendering. The process would be as following:
- Load the HTML file content into memory as a string
- Compile the template and store the compiled version in a Map or object
- Render from the compiled instance for a given file and send as string response with html content-type header
