### ISSUE TITLE
Debugging an issue on AWS ALB 502s

### ISSUE THREAD

**Issue by jsonmorris** [kartikk221/hyper-express#179]
Hey folks, I'm using hyper-express behind an AS ALB and running into the [very](https://repost.aws/knowledge-center/elb-alb-troubleshoot-502-errors). [well](https://www.tessian.com/blog/how-to-fix-http-502-errors/). [documented](https://iximiuz.com/en/posts/reverse-proxy-http-keep-alive-and-502s/). 502 problem with upstream TCP disconnects. We are seeing about 0.05% of requests being dropped with a 502 on the ALB.

Looking to the community for help debugging `hyper-express`, or `uSockets / uWebSockets` if that's where the issue is. As it stands, there's not a lot of tracing, logging, etc that is helpful for me.

Based on the following evidence, it seems that there's an issue with `uSockets` closing open connections with TCP RST/FIN before the AWS ALB timeout has elapsed. Interesting to note the `target_processing_time` here, where some requests look to be canceled near instantly `0.001s` where there are in flight for a considerable amount of time, `8s - 12s`.

<details><summary>logs table</summary>

|`request_processing_time`|`target_processing_time`|`response_processing_time`|`elb_status_code`|`received_bytes`|`sent_bytes`|
|--|--|--|--|--|--|
|0.003|0.0|-1.0|502|525|155|
|0.001|8.932|-1.0|502|2206|679|
|0.003|0.0|-1.0|502|525|155|
|0.026|0.001|-1.0|502|240|277|
|0.004|0.0|-1.0|502|359|277|
|0.005|0.001|-1.0|502|250|674|
|0.002|0.0|-1.0|502|527|155|
|0.003|0.0|-1.0|502|527|155|
|0.008|0.001|-1.0|502|173|277|
|0.004|0.001|-1.0|502|204|679|
|0.002|10.39|-1.0|502|23172|679|
|0.003|0.0|-1.0|502|196|679|
|0.007|0.0|-1.0|502|527|155|
|0.003|0.0|-1.0|502|525|155|
|0.007|0.001|-1.0|502|527|155|
|0.005|0.001|-1.0|502|206|679|
|0.005|0.001|-1.0|502|525|155|
|0.003|0.0|-1.0|502|185|272|
|0.001|10.031|-1.0|502|23173|679|
|0.005|8.711|-1.0|502|2285|679|
|0.001|3.608|-1.0|502|2553|277|
|0.001|11.615|-1.0|502|23172|679|
|0.005|0.001|-1.0|502|261|679|
|0.001|6.86|-1.0|502|297|272|
|0.004|0.0|-1.0|502|525|155|
|0.004|0.0|-1.0|502|527|155|
|0.01|0.001|-1.0|502|234|277|
|0.001|0.0|-1.0|502|2575|277|
|0.001|11.491|-1.0|502|297|272|
|0.001|0.375|-1.0|502|599|679|
|0.003|0.0|-1.0|502|359|277|
|0.004|0.001|-1.0|502|231|679|
|0.004|0.001|-1.0|502|527|155|
|0.001|0.0|-1.0|502|2286|679|
|0.003|0.0|-1.0|502|361|277|
|0.009|0.001|-1.0|502|527|155|
|0.004|0.0|-1.0|502|525|155|
|0.003|0.0|-1.0|502|230|679|
|0.006|0.001|-1.0|502|316|679|
|0.011|0.001|-1.0|502|326|277|
|0.006|0.001|-1.0|502|525|155|
|0.005|0.001|-1.0|502|221|272|
|0.065|1.691|-1.0|502|2193|679|
|0.003|0.0|-1.0|502|224|272|
|0.003|0.0|-1.0|502|220|674|
|0.08|9.732|-1.0|502|2280|679|
|0.081|8.272|-1.0|502|3180|679|
|0.001|3.747|-1.0|502|4540|679|
|0.006|11.332|-1.0|502|1940|679|
|0.005|0.001|-1.0|502|243|679|
|0.006|0.001|-1.0|502|230|679|
|0.004|0.0|-1.0|502|316|679|
|0.005|0.001|-1.0|502|525|155|
|0.008|0.0|-1.0|502|527|155|
|0.005|0.001|-1.0|502|256|674|
|0.004|0.001|-1.0|502|527|155|
|0.006|0.001|-1.0|502|230|679|
|0.006|0.001|-1.0|502|316|679|
|0.003|0.001|-1.0|502|214|674|
|0.004|0.001|-1.0|502|55|277|
|0.003|0.0|-1.0|502|231|679|
|0.037|0.0|-1.0|502|317|679|
|0.01|0.001|-1.0|502|43|277|
|0.003|0.0|-1.0|502|159|277|
|0.006|0.001|-1.0|502|234|679|
|0.001|0.0|-1.0|502|527|155|
|0.003|0.0|-1.0|502|204|674|
|0.001|0.001|-1.0|502|204|679|
|0.006|0.0|-1.0|502|274|277|
|0.004|0.001|-1.0|502|231|679|
|0.005|0.001|-1.0|502|317|679|
|0.003|0.0|-1.0|502|361|277|
|0.004|0.0|-1.0|502|271|679|
|0.003|0.0|-1.0|502|317|679|
|0.003|0.0|-1.0|502|231|679|
|0.071|0.007|-1.0|502|1961|679|
|0.008|0.0|-1.0|502|190|272|
|0.005|0.001|-1.0|502|234|277|
|0.006|0.001|-1.0|502|215|679|
|0.016|0.001|-1.0|502|326|277|
|0.009|0.0|-1.0|502|236|679|
|0.006|0.0|-1.0|502|525|155|
|0.006|0.001|-1.0|502|525|155|
|0.001|8.012|-1.0|502|297|272|
|0.005|0.001|-1.0|502|222|277|
|0.003|0.0|-1.0|502|361|277|
|0.005|0.001|-1.0|502|317|679|
|0.014|0.001|-1.0|502|231|679|
|0.029|0.001|-1.0|502|240|277|
|0.005|0.001|-1.0|502|184|277|
|0.003|0.0|-1.0|502|233|277|
|0.006|0.0|-1.0|502|234|679|
|0.002|0.0|-1.0|502|525|155|
|0.004|0.0|-1.0|502|42|272|
|0.004|0.0|-1.0|502|136|277|
|0.004|0.0|-1.0|502|203|277|
|0.007|0.001|-1.0|502|219|674|
|0.007|0.0|-1.0|502|527|155|
|0.001|0.001|-1.0|502|216|679|
|0.004|0.0|-1.0|502|231|679|
|0.003|0.0|-1.0|502|317|679|
|0.003|0.0|-1.0|502|527|155|
|0.006|0.001|-1.0|502|229|679|
|0.003|0.0|-1.0|502|525|155|
|0.007|0.0|-1.0|502|68|277|
|0.001|0.0|-1.0|502|105|277|
|0.003|0.0|-1.0|502|205|679|
|0.006|0.001|-1.0|502|205|679|
|0.004|0.001|-1.0|502|204|679|
|0.001|0.0|-1.0|502|527|155|
|0.091|11.21|-1.0|502|24149|679|
|0.001|8.434|-1.0|502|23173|679|
|0.062|8.697|-1.0|502|2037|679|
|0.001|8.444|-1.0|502|2821|277|
|0.005|0.001|-1.0|502|236|679|
|0.003|0.0|-1.0|502|527|155|
|0.012|0.0|-1.0|502|2069|679|
|0.009|0.002|-1.0|502|274|277|
|0.071|0.001|-1.0|502|2000|679|
|0.006|0.001|-1.0|502|316|679|
|0.002|0.0|-1.0|502|230|679|
|0.006|0.001|-1.0|502|242|272|
|0.005|0.001|-1.0|502|206|272|
|0.006|0.0|-1.0|502|325|277|
|0.001|4.815|-1.0|502|2123|679|
|0.003|0.0|-1.0|502|42|277|
|0.003|0.0|-1.0|502|158|277|
|0.005|0.001|-1.0|502|204|674|
|0.053|0.001|-1.0|502|240|277|
|0.006|0.001|-1.0|502|525|155|
|0.003|0.0|-1.0|502|316|679|
|0.004|0.0|-1.0|502|230|679|
|0.008|0.001|-1.0|502|254|272|
|0.009|0.001|-1.0|502|525|155|
|0.006|0.001|-1.0|502|305|674|
|0.005|11.45|-1.0|502|1940|679|
|0.001|9.396|-1.0|502|2032|679|
|0.003|0.0|-1.0|502|158|277|
|0.005|0.001|-1.0|502|527|155|
|0.003|0.0|-1.0|502|230|679|
|0.006|0.001|-1.0|502|316|679|
|0.001|1.124|-1.0|502|2280|679|
|0.009|0.001|-1.0|502|540|679|
|0.008|0.001|-1.0|502|504|679|
|0.003|0.0|-1.0|502|100|277|
|0.003|0.0|-1.0|502|200|679|
|0.004|0.0|-1.0|502|231|679|
|0.004|0.001|-1.0|502|317|679|
|0.009|0.0|-1.0|502|68|277|
|0.003|0.0|-1.0|502|263|679|
|0.004|0.0|-1.0|502|230|679|
|0.008|0.0|-1.0|502|234|679|
|0.001|2.543|-1.0|502|2110|679|
|0.001|9.208|-1.0|502|2291|679|
|0.003|0.0|-1.0|502|359|277|
|0.005|0.001|-1.0|502|243|674|
|0.004|0.001|-1.0|502|527|155|
|0.003|0.0|-1.0|502|527|155|
|0.004|0.0|-1.0|502|527|155|
|0.003|0.0|-1.0|502|263|679|
|0.001|4.743|-1.0|502|2069|679|
|0.001|9.521|-1.0|502|1946|679|
|0.007|0.0|-1.0|502|254|272|
|0.063|10.371|-1.0|502|2204|679|
|0.001|6.727|-1.0|502|3438|679|
|0.001|7.943|-1.0|502|23172|679|
|0.009|0.001|-1.0|502|158|277|
|0.005|0.001|-1.0|502|527|155|
|0.148|0.056|-1.0|502|2241|679|
|0.005|0.001|-1.0|502|43|272|
|0.005|0.001|-1.0|502|254|272|
|0.016|0.001|-1.0|502|249|679|
|0.01|0.0|-1.0|502|527|155|
|0.008|0.0|-1.0|502|527|155|
|0.006|0.001|-1.0|502|43|272|
|0.003|0.0|-1.0|502|360|674|
|0.003|0.0|-1.0|502|380|674|
|0.004|0.0|-1.0|502|370|674|
|0.003|0.0|-1.0|502|385|674|
|0.003|0.0|-1.0|502|230|679|
|0.003|0.0|-1.0|502|316|679|
|0.002|0.0|-1.0|502|211|679|
|0.003|0.0|-1.0|502|525|155|
|0.006|0.0|-1.0|502|527|155|
|0.005|0.001|-1.0|502|159|277|
|0.007|0.0|-1.0|502|159|277|
|0.006|0.001|-1.0|502|254|272|
|0.003|0.0|-1.0|502|243|679|
|0.008|0.0|-1.0|502|230|679|
|0.007|0.0|-1.0|502|316|679|
|0.003|0.0|-1.0|502|525|155|
|0.004|0.0|-1.0|502|231|679|
|0.001|0.001|-1.0|502|143|277|
|0.003|0.0|-1.0|502|159|277|
|0.001|10.109|-1.0|502|2248|679|
|0.001|0.0|-1.0|502|3135|679|
|0.006|0.001|-1.0|502|159|277|
|0.003|0.0|-1.0|502|43|277|
|0.005|0.0|-1.0|502|203|679|
|0.009|0.003|-1.0|502|259|277|
|0.005|0.001|-1.0|502|527|155|
|0.004|0.001|-1.0|502|219|679|
|0.008|0.0|-1.0|502|361|277|
|0.008|0.001|-1.0|502|241|679|
|0.01|0.0|-1.0|502|241|679|
|0.003|0.0|-1.0|502|253|679|
|0.003|0.0|-1.0|502|262|679|
|0.004|0.0|-1.0|502|241|679|
|0.003|0.0|-1.0|502|283|679|
|0.007|0.0|-1.0|502|319|679|
|0.003|0.0|-1.0|502|263|679|
|0.002|0.0|-1.0|502|277|679|
|0.003|0.0|-1.0|502|230|679|
|0.005|0.001|-1.0|502|527|155|
|0.006|0.001|-1.0|502|296|277|
|0.007|0.0|-1.0|502|382|277|
|0.003|0.0|-1.0|502|193|277|
|0.004|0.0|-1.0|502|101|277|
|0.005|0.0|-1.0|502|271|679|
|0.002|0.0|-1.0|502|2313|679|
|0.007|0.0|-1.0|502|243|679|
|0.003|0.0|-1.0|502|230|679|
|0.003|0.0|-1.0|502|42|277|
|0.006|0.001|-1.0|502|158|277|
|0.003|0.0|-1.0|502|527|155|
|0.003|0.0|-1.0|502|317|679|
|0.005|0.001|-1.0|502|231|679|
|0.001|0.0|-1.0|502|2053|679|
|0.003|0.0|-1.0|502|525|155|
|0.001|11.19|-1.0|502|23173|679|
|0.001|9.81|-1.0|502|2213|679|
|0.001|7.847|-1.0|502|3473|679|
|0.071|0.388|-1.0|502|4338|679|
|0.001|0.001|-1.0|502|216|679|
|0.001|1.029|-1.0|502|2083|679|
|0.009|0.001|-1.0|502|220|674|
|0.041|0.001|-1.0|502|239|277|
|0.001|10.941|-1.0|502|1620|277|
|0.07|7.112|-1.0|502|1999|679|
|0.011|0.0|-1.0|502|527|155|
|0.009|0.001|-1.0|502|527|155|
|0.003|0.0|-1.0|502|699|679|
|0.003|10.505|-1.0|502|2251|679|
|0.004|0.0|-1.0|502|263|679|
|0.001|7.427|-1.0|502|1620|277|
|0.001|6.66|-1.0|502|2180|679|
|0.007|0.0|-1.0|502|326|277|
|0.004|0.0|-1.0|502|222|272|
|0.004|0.0|-1.0|502|193|272|
|0.005|0.0|-1.0|502|231|679|
|0.006|0.001|-1.0|502|317|679|
|0.004|0.0|-1.0|502|213|679|
|0.008|0.0|-1.0|502|236|679|
|0.005|0.001|-1.0|502|246|679|
|0.011|0.0|-1.0|502|527|155|
|0.003|0.0|-1.0|502|159|277|
|0.003|0.0|-1.0|502|159|277|
|0.006|0.0|-1.0|502|527|155|
|0.01|0.0|-1.0|502|43|277|
|0.005|0.001|-1.0|502|159|277|
|0.003|0.0|-1.0|502|76|277|
|0.009|0.001|-1.0|502|527|155|
|0.003|0.0|-1.0|502|182|277|
|0.009|0.001|-1.0|502|231|679|
|0.001|6.072|-1.0|502|2130|679|
|0.004|0.0|-1.0|502|326|277|
|0.004|0.0|-1.0|502|267|272|
|0.005|0.001|-1.0|502|260|277|
|0.001|11.049|-1.0|502|4338|679|
|0.001|10.246|-1.0|502|2377|277|
|0.001|8.06|-1.0|502|2213|679|
|0.001|8.636|-1.0|502|24132|679|
|0.001|10.642|-1.0|502|3055|679|
|0.005|0.001|-1.0|502|200|679|
|0.003|0.0|-1.0|502|211|679|
|0.003|0.0|-1.0|502|102|277|
|0.006|0.001|-1.0|502|272|679|
|0.001|0.0|-1.0|502|234|277|
|0.003|0.0|-1.0|502|527|155|
|0.001|3.427|-1.0|502|2186|679|
|0.001|8.819|-1.0|502|2036|679|
|0.002|10.29|-1.0|502|2186|679|
</details>

This seems to align with known behavior on ALBs [according to AWS](https://repost.aws/knowledge-center/elb-alb-troubleshoot-502-errors).

> The target closed the connection with a TCP RST or a TCP FIN while the load balancer had an outstanding request to the target

> The load balancer receives a request and forwards it to the target. The target receives the request and starts to process it, but closes the connection to the load balancer too early. This usually occurs when the duration of the keep-alive timeout for the target is shorter than the idle timeout value of the load balancer. Make sure that the duration of the keep-alive timeout is greater than the idle timeout value.

> Check the values for the request_processing_time, target_processing_time and response_processing_time fields.

> In this access log entry, the request_processing_time is 0.001, the target_processing_time is 4.205, and the response_processing_time is -1.

I'm also curious if you're run into any issues with the [static timeout values in uWebSockets ](https://github.com/uNetworking/uWebSockets/issues/1242). Are there any prior reports of `hyper-express` running into this 502 issue on existing deployments?

Given these, a few things to follow up on:

- I've tried changing the AWS ALB `idleTimeout` values to `9s` and `7s`, which I assumed would help offset this hardcoded timeout of 10s. However, _neither_ of these values showed a decrease in 502s. 

- AWS mentions that this same issue may be due to [malformed requests](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html). 
  >  This value is set to -1 if the load balancer doesn't receive a response from a target. This can happen if the target closes the connection before the idle timeout or if the client sends a malformed request.
  
  Is there a way to turn on logging for bad requests on the server?

**Comment by kartikk221** [comment]
Hey, your write up seems to be great and detailed. While `hyper-express` adds a lot of features on top of `uWebsockets.js`, It is fundamentally just a wrapper that doesn't mess with the actual request lifecycle of a uWS.HttpRequest. For that reason, It is very likely that the bug you are running into is caused due to a problem with uWebsockets.js itself. I would highly recommend you make this issue in the uWebsockets.js repositroy so the maintainer of uWebsockets.js can provide more information on this problem.

I do recall that uWebsockets.js tends to timeout requests and connections in an interval that is a factor of 4. While I don't see why that would be a problem, It may be a starting point or in some way linked to the weird cancelation times ranging from `0.001s` all the way up to `8 - 12s`.

Hope the above helps and I'll be following you issue in `uWebsockets.js` closely in case any changes are needed to `hyper-express.

**Comment by kartikk221** [comment]
One additional follow up question I have is does the endpoint which suffers from the 502s consume the incoming request body (If any) as a stream?

**Comment by jsonmorris** [comment]
> back-pressure

I looked through some of the uws/usocket code and it looks like back-pressure only applies to `ws` connections. We're only serving `http` at this point, or do I misunderstand the behavior here?

**Comment by kartikk221** [comment]
> > back-pressure
> 
> 
> 
> I looked through some of the uws/usocket code and it looks like back-pressure only applies to `ws` connections. We're only serving `http` at this point, or do I misunderstand the behavior here?

So back-pressure can apply to HTTP as well. For example, let's say you are receiving a large request body and are further streaming it to your filesystem by piping the request to a writable. It is possible that this writable experiences back-pressure as the filesystem of your machine is stressed. In this scenario, hyper-express will pause the uWS.HttpRequest effectively pausing any more body chunks from being received as to not exhaust the memory while the back-pressure drains. Once the back-pressure has been drained, hyper-express will resume the Request to begin receiving and piping more body chunks until completion.

**Comment by jsonmorris** [comment]
@kartikk221 Thanks for that explanation. To be clear, there's no back pressure setting for http routes that I need could tweak [like there is for `ws` routes?](https://github.com/uNetworking/uWebSockets.js/blob/c187e4f84c76d9c225d3615ae1326b2db5c4085f/README.md?plain=1#L29)

**Comment by kartikk221** [comment]
@jsonmorris No, this is not something you can tweak as it is implemented by `hyper-express` to automatically minimize memory usage for large body streams.

**Comment by jsonmorris** [comment]
@kartikk221 would be available to bump `uws.js` to [v20.31.0](https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.31.0?).

**Comment by kartikk221** [comment]
> @kartikk221 would be available to bump `uws.js` to [v20.31.0](https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.31.0?)?

Sure, any changes I should be aware that need to be implemented or is this just a version bump to bugfix?

**Comment by jsonmorris** [comment]
It's a similar change to `v20.30.0`, which I see you've already adopted. It adds an additional default 404 error code for unmatched routes.

**Comment by kartikk221** [comment]
I see, ok. Yeah hyper-express adds a default 500 error handler but not a not found handler. You can specify one with `Server.set_not_found_handler()` but I'll bump version so the native defaults work to handle those proxy errors. I've also noticed browsers don't like it when a webserver instantly closes a connection without any route found.

**Comment by kartikk221** [comment]
@jsonmorris Try `hyper-express` version 6.7.3 to see If that resolves your issue.
