### ISSUE TITLE
Error : 413 Payload Too Large

### ISSUE THREAD

**Issue by muamarhm** [kartikk221/hyper-express#191]
413 Payload Too Large. I get an error payload too large, how do I increase it max_body_length ? 

```
import HyperExpress from 'hyper-express'
import {
  create
} from '../../../controllers/admin/campaign/index.js'
const router = new HyperExpress.Router()
router.post(
  '/',
  {
    max_body_length: 100, //100 Mb
  },
  create
)
```

![image](https://github.com/kartikk221/hyper-express/assets/11833253/4c26f2d4-c763-41f8-a189-4f0974c65cda)

**Comment by kartikk221** [comment]
I am assuming you have solved this already but in case not, the `max_body_length` and any payload size length parameter in `hyper-express` is in bytes hence `100MB` would be `1024 * 1024 * 100`
