### ISSUE TITLE
LiveDirectory.md is outdated

### ISSUE THREAD

**Issue by dimdenGD** [kartikk221/hyper-express#196]
https://github.com/kartikk221/hyper-express/blob/master/docs/LiveDirectory.md
- there's no more "path" option and first argument is used for that instead
- `keep` and `ignore` options should be inside `filter` object now
- `buffer` was replaced with `content`
- doesn't explain how caching works and how to handle uncached files

**Comment by kartikk221** [comment]
Hi, I have updated the docs at https://github.com/kartikk221/hyper-express/blob/master/docs/LiveDirectory.md to be up to date. Let me know If there are any other concerns that should be addressed in the docs.
