### ISSUE TITLE
`res.cookie` is incompatible with express

### ISSUE THREAD

**Issue by dimdenGD** [kartikk221/hyper-express#204]
Line: https://github.com/kartikk221/hyper-express/blob/eb0b4675f7941e9b77c3d9fab94811012b0bcc23/src/components/http/Response.js#L241
hyper-express: `cookie(name, value, expiry, options, sign_cookie = true)`  
vs  
express: `res.cookie(name, value [, options])` http://expressjs.com/en/4x/api.html#res.cookie  

Also `options.expires` in express accepts Date for when it should expire, while hyper-express accepts Number of milliseconds before expiry

**Comment by kartikk221** [comment]
Hi, changing the function of the `Response.cookie()` method would be a breaking change hence it is planned for the next major update which is in the works and will bring closer compatibility.
