### ISSUE TITLE
 How to use `compression`?

### ISSUE THREAD

**Issue by o-az** [kartikk221/hyper-express#206]
Trying to use this middleware: https://www.npmjs.com/package/compression.

Tried the following but no luck

```ts
import compression from 'compression'
import HyperExpress from 'hyper-express'

const server = new HyperExpress.Server()

function shouldCompress(request: HyperExpress.Request, response: HyperExpress.Response) {
  if (request.headers['x-no-compression']) return false
  return compression.filter(request, response)
}

// compress all responses
server.use((request, response, next) => {
  const compress = compression({ filter: shouldCompress })
  return compress(request as any, response, next)
})
```

Also tried following [express guide](https://expressjs.com/en/resources/middleware/compression.html), no luck:
```ts
import compression from 'compression'
import HyperExpress from 'hyper-express'

const server = new HyperExpress.Server()

function shouldCompress(request: HyperExpress.Request, response: HyperExpress.Response) {
  if (request.headers['x-no-compression']) return false
  return compression.filter(request, response)
}

// compress all responses
server.use(compression({ filter: shouldCompress }))
```

I'm testing it with `curl --head`

**Comment by kartikk221** [comment]
Hey, this middleware does not seem to be maintained anymore given by the last publish 5 years ago. I am assuming it is depending on an old compatibility method or behavior from Express. When you use it with `hyper-express`, what if any errors / stack traces do you see in the console?

**Comment by o-az** [comment]
@kartikk221 
```ts
import HyperExpress from 'hyper-express'
import compression from 'compression'

const server = new HyperExpress.Server()

function shouldCompress(request: HyperExpress.Request, response: HyperExpress.Response) {
  if (request.headers['x-no-compression']) return false
  return compression.filter(request, response)
}

server.use((request, response, next) => {
  const compress = compression({ filter: shouldCompress })
  return compress(request, response, next)
})

server.all('/', (request, response, _) => response.send('Hello World'))

const PORT = Number(process.env.PORT ?? 3034)
server.listen(PORT)
```

```sh
curl http://localhost:3034 --head
```
```sh
# no compression headers
HTTP/1.1 200 OK
Date: Wed, 22 Nov 2023 03:34:49 GMT
Content-Length: 11
```

Type errors:

`compression.filter` request and response arguments types are incompatible with HE request type:
```ts
Argument of type 'Request<DefaultRequestLocals>' is not assignable to parameter of type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
  Type 'Request<DefaultRequestLocals>' is missing the following properties from type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>': accepted, host, route, signedCookies, and 13 more.ts(2379)
```
![CleanShot 2023-11-21 at 19 36 08@2x](https://github.com/kartikk221/hyper-express/assets/23618431/9a33a764-1152-4a54-9f02-12353b6af519)

**Comment by kartikk221** [comment]
So is the incompatibility just TypeScript types or is it a functional incompatibility? I notice that you said there are no compression headers added, so the middleware is just not running at all?

**Comment by o-az** [comment]
> So is the incompatibility just TypeScript types or is it a functional incompatibility? I notice that you said there are no compression headers added, so the middleware is just not running at all?

Yes not running at all. It seems to have no effects

**Comment by kartikk221** [comment]
I see, that likely means there is some method / property which is incompatible under the hood. For now, HyperExpress has limited compatibility with Express.js and this would be one of the cases where this middleware is just not compatible. The likely reason is that the middleware is old and not maintained anymore so it likely depends on an older and more obscure property/method from Express that is not supported at the moment.

The next major version update will make some breaking changes to increase the compatibility with Express, so that might resolve your issue in the future but for now this middleware would be incompatible.

**Comment by Geo25rey** [comment]
@o-az Looks like this is not an incompatibility with `hyper-express` (besides type errors).

The `compression` library seems to require the "Content-Type" header to properly understand if the content is compressible. See the `compressible` library for details. Here's excerpt from `compressible`'s README explaining the filter logic:

> The MIME is looked up in the [mime-db](https://www.npmjs.com/package/mime-db) and if there is compressible information in the database entry, that is returned. Otherwise, this module will fallback to true for the following types:
>
> - text/*
> - \*/\*+json
> - \*/\*+text
> - \*/\*+xml

#### Word of advice:
Next time you encounter an old Node.JS library you want to use with little documentation (it will happen), look at the source code. They are typically 1 short JS file with decently readable code, especially if they have multiple dependencies.
