### ISSUE TITLE
Default Encoding problems with accents

### ISSUE THREAD

**Issue by Trystan-SA** [kartikk221/hyper-express#209]
Hey. I'm trying to send a response messages that contain accents `é`, `à`, `ù`.
 
JSON encoding work well.
```ts
res.status(500).json({'é': 'à'}) 
// print : {"é":"à"}
```

But others methods don't work by default (or by using UTF8 encoding).
```ts
res.status(500).write('é à ù', 'utf8') 
res.send()
// print : Ã© Ã  Ã¹

res.status(500).send('é à ù') 
// print : Ã© Ã  Ã¹

res.status(500).html('é à ù')
// print : Ã© Ã  Ã¹
```

Creating a middleware that set the content type globally make it work.
```ts
res.header('Content-Type', 'text/html; charset=utf-8')
```

It's not a big issue, but I think encoding should be set to UTF8 by default.

(awesome package by the way, it's a real pleasure to use !)

**Comment by kartikk221** [comment]
Hi, thanks for catching this error. This should be fixed in the latest `v6.14.5` update. It seems that `Response.type()` was incorrectly just resolving the content-type instead of the full header from the underlying `mime-types` library hence the charset was not being specified.
