### ISSUE TITLE
Handling multiple multipart

### ISSUE THREAD

**Issue by ch3rn1k** [kartikk221/hyper-express#211]
Hello! Any advice how can I handle multiple file upload? Sometimes it works fine, uploading all files and returning urls, but sometimes `res.json()` calls in the middle of all files or after first iteration. Thanks

Latest version used

My sample:

```ts
const filesUrl: IFile[] = [];

await req.multipart(async (field) => {
  if (field.file && field.mime_type.startsWith('image/')) {
    await field.write(dirPath + '/' + uniqueFileName);
    filesUrl.push(dirPath + '/' + uniqueFileName);
  }
});

if (filesUrl.length) {
  res.json({
    status: 'ok',
    message: 'Successfully uploaded a file(s)',
    data: filesUrl
  });
} else {
  res.status(500).json({
    status: 'error',
    message: 'Internal server error'
  });
}
```

**Comment by kartikk221** [comment]
Hello, the `Request.multipart()` returns a promise which will not resolve until all of the callback fields have been handled. The only reason I can see some of your files not being uploaded is If the mime type is something else you are not expecting and hence that file is skipped and response is sent without uploading anything.

I would modify your code snippet like this to find out which fields are being skipped and possibly improve your if statement to ensure those valid files are not skipped.

Modified snippet:
```js
await req.multipart(async (field) => {
  if (field.file && field.mime_type.startsWith('image/')) {
    await field.write(dirPath + '/' + uniqueFileName);
    filesUrl.push(dirPath + '/' + uniqueFileName);
  } else {
    console.log('skipped', {
        field,
        is_file: field.file,
        mime_type: field.mime_type,
    });
  }
});
```

**Comment by ch3rn1k** [comment]
> Hello, the `Request.multipart()` returns a promise which will not resolve until all of the callback fields have been handled. The only reason I can see some of your files not being uploaded is If the mime type is something else you are not expecting and hence that file is skipped and response is sent without uploading anything.
> 
> I would modify your code snippet like this to find out which fields are being skipped and possibly improve your if statement to ensure those valid files are not skipped.
> 
> Modified snippet:
> 
> ```js
> await req.multipart(async (field) => {
>   if (field.file && field.mime_type.startsWith('image/')) {
>     await field.write(dirPath + '/' + uniqueFileName);
>     filesUrl.push(dirPath + '/' + uniqueFileName);
>   } else {
>     console.log('skipped', {
>         field,
>         is_file: field.file,
>         mime_type: field.mime_type,
>     });
>   }
> });
> ```

Thanks for reply, but my problem aint by this (tested you idea). Some mystic is over here. More complex code:

```ts
await req.multipart(async (field) => {
    if (field.file && field.mime_type.startsWith('image/')) {
      const uniqueFileName = `${randomUUID()}.${mime.extension(field.mime_type)}`;
      const dirPath = path.join(process.env.CDN_PATH!, 'uploads', String(user._id));

      fs.mkdirSync(dirPath, { recursive: true });
      await field.write(dirPath + '/' + uniqueFileName);

      const fileBuffer = fs.readFileSync(dirPath + '/' + uniqueFileName);
      const hashSum = createHash('md5');
      hashSum.update(fileBuffer);

      const hashSumHex = hashSum.digest('hex');

      let fileInDatabase = await File.findOne({ hash: hashSumHex });
      if (!fileInDatabase) {
        if (mime.extension(field.mime_type) === 'gif') {
          fs.renameSync(dirPath + '/' + uniqueFileName, dirPath + '/' + hashSumHex + '.gif');
        } else {
          await sharp(fileBuffer)
            .webp({ quality: 90 })
            .toFile(dirPath + '/' + hashSumHex + '.webp');
          fs.unlinkSync(dirPath + '/' + uniqueFileName);
        }

        fileInDatabase = await File.create({
          user: user._id,
          name: field.file.name ? path.parse(field.file.name).name : '',
          url:
            process.env.CDN_ADDRESS! +
            '/' +
            user._id +
            '/' +
            hashSumHex +
            '.' +
            (mime.extension(field.mime_type) === 'gif' ? 'gif' : 'webp'),
          mime: field.mime_type,
          hash: hashSumHex
        });
      } else {
        fs.unlinkSync(dirPath + '/' + uniqueFileName);
      }

      console.log('Pushing data...');
      filesUrl.push(fileInDatabase);
    } else {
      console.log('Wrong file!');
    }
  });

  console.log('Finished!');

  if (filesUrl.length) {
    res.json({
      status: 'ok',
      message: 'Successfully uploaded a file(s)',
      data: filesUrl
    });
  } else {
    res.status(500).json({
      status: 'error',
      message: 'Internal server error'
    });
  }
```

I was testing uploading 8 files same time:
```
Pushing data...
Pushing data...
Pushing data...
Pushing data...
Pushing data...
Pushing data...
Pushing data...
Finished!
Pushing data...
```

```
Pushing data...
Pushing data...
Pushing data...
Pushing data...
Pushing data...
Finished!
Pushing data...
Pushing data...
Pushing data...
```

**Comment by ch3rn1k** [comment]
Ah, you mean when `await field.write()` called - it ignores next async functions? Damn
Any way to handle this with async for each item until end? Ty

**Comment by kartikk221** [comment]
I think I may know what is happening. It seems that you do a lot of async processing on each file field. It seems that Response.multipart() promise resolves once the stream is complete meaning the last Field.write() is complete but you still have more async work to do. So this is likely a bug and I'll look into it to see If it can be resolved.

**Comment by ch3rn1k** [comment]
> I think I may know what is happening. It seems that you do a lot of async processing on each file field. It seems that Response.multipart() promise resolves once the stream is complete meaning the last Field.write() is complete but you still have more async work to do. So this is likely a bug and I'll look into it to see If it can be resolved.

Thanks! For now I used async for next loop and it works as expected :)

```ts
const filesRaw: {
  dirPath: string;
  uniqueFileName: string;
  mimeType: string | boolean;
  fileName: string;
}[] = [];
const filesUrl: IFile[] = [];

await req.multipart(async (field) => {
  if (field.file && field.mime_type.startsWith('image/')) {
    const uniqueFileName = `${randomUUID()}.${mime.extension(field.mime_type)}`;
    const dirPath = path.join(process.env.CDN_PATH!, 'uploads', String(user._id));

    fs.mkdirSync(dirPath, { recursive: true });

    filesRaw.push({
      dirPath,
      uniqueFileName,
      mimeType: mime.extension(field.mime_type),
      fileName: field.file.name ? path.parse(field.file.name).name : ''
    });
    await field.write(dirPath + '/' + uniqueFileName);
  }
});

for (let i = 0; i < filesRaw.length; i++) {
  const fileBuffer = fs.readFileSync(filesRaw[i].dirPath + '/' + filesRaw[i].uniqueFileName);
  const hashSum = createHash('md5');
  hashSum.update(fileBuffer);

  const hashSumHex = hashSum.digest('hex');

  let fileInDatabase = await File.findOne({ hash: hashSumHex });
  if (!fileInDatabase) {
    if (filesRaw[i].mimeType === 'gif') {
      fs.renameSync(filesRaw[i].dirPath + '/' + filesRaw[i].uniqueFileName, filesRaw[i].dirPath + '/' + hashSumHex + '.gif');
    } else {
      await sharp(fileBuffer)
        .webp({ quality: 90 })
        .toFile(filesRaw[i].dirPath + '/' + hashSumHex + '.webp');
      fs.unlinkSync(filesRaw[i].dirPath + '/' + filesRaw[i].uniqueFileName);
    }

    fileInDatabase = await File.create({
      user: user._id,
      name: filesRaw[i].fileName,
      url:
        process.env.CDN_ADDRESS! + '/' + user._id + '/' + hashSumHex + '.' + (filesRaw[i].mimeType === 'gif' ? 'gif' : 'webp'),
      mime: filesRaw[i].mimeType,
      hash: hashSumHex
    });
  } else {
    fs.unlinkSync(filesRaw[i].dirPath + '/' + filesRaw[i].uniqueFileName);
  }

  filesUrl.push(fileInDatabase);
}

if (filesUrl.length) {
  res.json({
    status: 'ok',
    message: 'Successfully uploaded a file(s)',
    data: filesUrl
  });
} else {
  res.status(500).json({
    status: 'error',
    message: 'Internal server error'
  });
}
```

**Comment by kartikk221** [comment]
Yeah downloading all files to disk and then doing post processing is likely a better pattern because If you do async work between fields then the whole Request body stream has to be paused and this may cause the client to timeout / kill the request. But with this approach body is downloaded first fully then post work done. I will still look into the other bug as while not ideal it should work as intended.

**Comment by kartikk221** [comment]
Hey, your old logic should now work with the new `v6.14.7` update as it now awaits the async execution of the last field / file instead of simply relying on the body stream to be fully received.
