### ISSUE TITLE
Feature request: swagger

### ISSUE THREAD

**Issue by vanvuongngo** [kartikk221/hyper-express#214]
Hi there,

your project is looking promising. Are there any plans to provide a swagger/ OpenAPI spec plugin?
like https://www.npmjs.com/package/@elysiajs/swagger

best regards

**Comment by kartikk221** [comment]
There aren't any plans of that at the moment for something like above. 

With that said, the community is more than welcome to write their own middlewares on top of `hyper-express` as the one you mentioned with Elysia. 

My current major goal for `hyper-express` is to lower the API / compatibility gap (Maybe even no gap) with Express.js in the next major version change.
