### ISSUE TITLE
No error thrown if invalid json is sent as body 

### ISSUE THREAD

**Issue by geminigeek** [kartikk221/hyper-express#215]
hi,
issue is same as title , here is what i tested with vscode http client, sending invalid json makes body empty , no error is thrown even when the correct headers are set 

check coma after "test2"
```
POST http://127.0.0.1:3000/
content-type: application/json

{
  "arg1":"test",
  "arg2":"test2",
}

``` 

Expected result: should throw some error on invalid json

**Comment by kartikk221** [comment]
Hi, as mentioned in the docs, the Response.json() is a safe by default method. It has a signature of Response.json(default_value = {}). If the incoming JSON parsing fails, then the method returns the default_value. If you call the method with a falsy value like Response.json(undefined) or Response.json(null), then it will throw the underlying parse error on invalid JSON.

**Comment by Jiahonzheng** [comment]
I think it would be better if the parsing error is throwed by "reject" method of Promise. So that we can catch this error from the location we call "await request.json()".

https://github.com/kartikk221/hyper-express/blob/master/src/components/http/Request.js#L541

**Comment by kartikk221** [comment]
Hey, good catch, that is a bug. It shou ld be a reject call instead of a throw. Do you want to make a PR or should I push the change?

**Comment by Jiahonzheng** [comment]
Ok, I will make a PR!
