### ISSUE TITLE
writeHead implementation differs, causing an error

### ISSUE THREAD

**Issue by snowbldr** [kartikk221/hyper-express#22]
The implementation of the undocumented expressJS compatibility method Response.writeHead is different than what the express implementation was. The express writeHead takes a status code, an optional reasonPhrase, and an object with all of the headers. 

If an existing express application is using this method the way it was implemented in express, it causes the following exception when the end point gets hit: 

```js
 Error: Text and data can only be passed by String, ArrayBuffer or TypedArray.
        at /project/node_modules/hyper-express/src/components/http/Response.js:299:75
        at Array.forEach (<anonymous>)
        at /project/node_modules/hyper-express/src/components/http/Response.js:299:37
        at Array.forEach (<anonymous>)
        at Response._initiate_response (/project/node_modules/hyper-express/src/components/http/Response.js:298:40)
        at Response.write (/project/node_modules/hyper-express/src/components/http/Response.js:346:18)
```

This is because the status code gets used as the header name, and the object containing the headers gets used as the header value. 

The writeHead method appears to have been removed from express in 2014 https://github.com/expressjs/express/commit/74f55a863a63dcc40d5cc595582ca27e3018fe70

Given that it's been removed from express, this method should be removed from hyper-express. I think having a missing method is a better user experience, because the fix is to obviously use a different method. The current state is very confusing.

**Comment by kartikk221** [comment]
Good catch, This method has been removed in version 5.4.2.
