### ISSUE TITLE
Nest-hyper-express-adapter middleware tests failing

### ISSUE THREAD

**Issue by smolinari** [kartikk221/hyper-express#220]
Hi,

These two test suites are failing all tests: 

https://github.com/m8a-io/hyper-express-adapter/blob/dev/apps/hyper-express-test-app/tests/hello-world/e2e/exclude-middleware-hyper-express.spec.ts

https://github.com/m8a-io/hyper-express-adapter/blob/dev/apps/hyper-express-test-app/tests/hello-world/e2e/include-middleware.spec.ts

https://github.com/m8a-io/hyper-express-adapter/blob/dev/apps/hyper-express-test-app/tests/hello-world/e2e/middleware-class.spec.ts

With this error:

![image](https://github.com/kartikk221/hyper-express/assets/3314957/3c681936-1f9f-4bf2-9934-67414c617cbf)

Coming from here: https://github.com/kartikk221/hyper-express/blob/ee425e4d05ca7819e090396a9880c00789ae5c1a/src/components/router/Router.js#L258

They work with Express (as all the tests are taken directly from Nest's Express e2e tests). Any chance to make them work with Hyper Express?

If you need any help with the repo/ testing setup, please let me know. 

Scott

**Comment by kartikk221** [comment]
Hi, the middleware and overall Route system for hyper-express is incompatible with Express.js at the moment. This plans to be improved in the next major version upgrade. For now, middlewares are calculated and executed in the following manner:
- Global (Matches all patterns)
- Local (Matches specific routes' patterns)
- Route Specific (Matches just the specific route)

**Comment by smolinari** [comment]
Hi Kartik,

Thanks for the reply. When do you expect the next major version to be worked on/ released?

Scott

**Comment by kartikk221** [comment]
Hey, so re-doing the middleware / route system to be compatible with Express will be a decent undertaking and I'm planning to release it in about a few weeks from now. There's also other features / incompatibilities that will be addressed.

**Comment by smolinari** [comment]
Awesome! Looking forward to it! Can you start an issue for updates on the work so I can follow it please?
 
Scott
