### ISSUE TITLE
Outdated example of static serving / LiveDirectory

### ISSUE THREAD

**Issue by benjaco** [kartikk221/hyper-express#223]
The example at [docs/LiveDirectory.md](https://github.com/kartikk221/hyper-express/blob/master/docs/LiveDirectory.md) is outdated

The `Server.get` handler uses the `extension` property from the [LiveFile class in Live Directory](https://github.com/kartikk221/live-directory/blob/3.0.3/src/components/LiveFile.js) which issn't included in version 3 of Live Directory, latest version with this extension is [Version 2](https://github.com/kartikk221/live-directory/blob/2.3.2/src/components/LiveFile.js)

**Comment by kartikk221** [comment]
Hi, good catch. Do you want to make a PR with the fix or would you like me to make the change? I believe version 2 used to simply split by `.` and take the last part as the extension, possibly something similar could be done now.
