### ISSUE TITLE
Error: uWS.HttpResponse must not be accessed after uWS.HttpResponse.onAborted callback

### ISSUE THREAD

**Issue by josejooj** [kartikk221/hyper-express#224]
👋 Hello! I have an API running with **Hyper-Express**, and after the last update i observed that my API turns down every ~5-60 minutes

After some analysis, i observed this following error:

![image](https://github.com/kartikk221/hyper-express/assets/76636096/068efeb7-413d-4fad-bfd5-5923ed61ac8a)

But i'm already checking if the response if aborted, i only send the response in 3 locales:

```ts
// In CORS Middleware
if (response.route.method === 'OPTIONS' && !response.aborted) {
    response.statusCode = 204;
    return response.send("")
}

// In Rate-Limit middleware
if (limited && !res.aborted) return res.atomic(() => res
    .status(429)
    .send()
);

// This is a function to facilitate my work
// If i want to change something with the response send, i only change this function
// All routes send the response with <Response>._send - More than 200 results when i search "_send"
res._send = async (status, data) => {
    if (!res.aborted) res.status(status).json('noReturn' in req.query_parameters && status === 200 ? undefined : data)
    ... // other things, like logtail
}
```

So, what can i do to solve this? I imagine there is a problem with the module, since I check everywhere if the request was aborted...

Note: When i started to write this post (40 minutes ago), the API turns down again, but now i did a rollback to `v6.14.8`, and so far it's working, if the api turn down, i'll come back

Additional informations:

- **Node.js version**: `v20.11.0`
- **Operational System**: `Ubuntu 22.04`
- **Hyper-Express version**: `v6.14.11`
- **My Server options**: 
```ts
const server = new HyperExpress.Server({
    fast_buffers: true,
    ssl_prefer_low_memory_usage: true,
    trust_proxy: true
});
```

**Comment by kartikk221** [comment]
Hey, this bug should be fixed in the latest version `v6.14.12`.

Also, the Examples docs used to show usage of the `Response.atomic(() => {})` to improve performance but it was outdated and you no longer have to use `Response.atomic()` yourself anymore in your code as `hyper-express` automatically calls this method internally for most optimal performance and proper usage as needed with `uWebsockets.js`
