### ISSUE TITLE
Static serving

### ISSUE THREAD

**Issue by benjaco** [kartikk221/hyper-express#227]
Is there any update on `serve-static`, I have run into a case where `LiveAssets.get` returns a file where `.content` is undefined even when the full path in the `this.#options.path` in `LiveFile` is valid.

I can see you mentioned it in #124, but thats the only trace I can find of it

**Comment by kartikk221** [comment]
> Is there any update on `serve-static`, I have run into a case where `LiveAssets.get` returns a file where `.content` is undefined even when the full path in the `this.#options.path` in `LiveFile` is valid.
> 
> 
> 
> I can see you mentioned it in #124, but thats the only trace I can find of it

Hi, development of serve-static is paused at the moment as I am prioritizing other open source development with my limited time outside of commercial work.

Regarding, some files with live-directory having an undefined content, that is expected and will occur for certain files which are larger than the maximum file cache size. Essentially, LiveDirectory will load all files under the cache size and count limits into memory for performance. For the rest of files, you should use the stream() method to stream the file as the response.
