### ISSUE TITLE
Request hangs indefinitely if response.send throws an error

### ISSUE THREAD

**Issue by snowbldr** [kartikk221/hyper-express#23]
I encountered an issue where the request will hang indefinitely (likely causing a memory/connection leak). 

This happens when send is called with an invalid body. Normally, the error handler would pick up the failure and send a failure response. However, since the request is marked completed, send returns immediately and doesn't call the end method in the error handler. 

Here's an example to reproduce this issue:
```js
const server = new (require('hyper-express')).Server()

server.get('/', (req, res)=>{
    console.log("end point hit")
    res.send({foo:'bar'})
})

server.set_error_handler((req, res, err) => {
    console.log("Error handler hit")
    res.send("this will never send")
})

server.listen(8080)
```

I think, it might be fixed by not setting completed to true until after raw_response.end is called.

**Comment by kartikk221** [comment]
Oh I see, I've moved the call to mark request as completed into the if statement checking whether the response was sent successfully. This should prevent errors like above from version 5.4.2 onwards.
