### ISSUE TITLE
Listen on IPv6 by default

### ISSUE THREAD

**Issue by maxpain** [kartikk221/hyper-express#236]
Hello. Currently, the `listen` function only starts the `HyperExpress` server on the IPv4 address `0.0.0.0` but doesn't listen on IPv6.
I think it should also bind on `::`

**Comment by kartikk221** [comment]
Hey, If this change would be compatible across Windows, Linux and MacOS then I would be more than glad to merge it through a PR. Feel free to make the PR when you have the validation this should be a reverse compatible and non breaking change.
