### ISSUE TITLE
missing Promise return type on shutdown

### ISSUE THREAD

**Issue by Viper-Bit** [kartikk221/hyper-express#245]
shutdown return type in ts must be `Promise<boolean>` instead of `boolean`
https://github.com/kartikk221/hyper-express/blob/1f361259e032db6a38ce1cd5a7e0920b40784f60/types/components/Server.d.ts#L56-L62

typescript complain about using await on it:
``
Unexpected `await` of a non-Promise (non-"Thenable") value.
``

**Comment by kartikk221** [comment]
Hey, this has been merged and pushed in the recent `v6.15.2` version.
