### ISSUE TITLE
run on aws lambda

### ISSUE THREAD

**Issue by ianzone** [kartikk221/hyper-express#247]
Hi, the benchmark is amazing. I'm wondering how to deploy hyper-express to aws lambda using the serverless framework, and how would it perform compared to [serverless-express](https://github.com/CodeGenieApp/serverless-express).

**Comment by kartikk221** [comment]
HyperExpress is a **webserver** hence it isn't suited for serverless (I don't even think serverless applies here unless I am mistaken). 

I am pretty sure each request on a serverless platform is handled with different contexts hence what you linked with `serverless-express` is just a handler which wraps the native Request/Response from the platform with Express APIs. It doesn't actually act as a webserver in any way and the performance of serverless throughput is fully controlled by the platform which is scaling the incoming request not the JS or logic.
