### ISSUE TITLE
Middleware goes beyond the Router

### ISSUE THREAD

**Issue by FullmetalBober** [kartikk221/hyper-express#252]
So this issue occurs, when in router_1 we using local for this router middleware, but this middleware also appears in router_2

[codesandbox reproduse](https://codesandbox.io/p/devbox/hyper-expres-router-bug-vgjpfw?file=%2Findex.js%3A14%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvf4iehc0006356mnw7ll4n9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvf4iehb0002356mirzf8yw5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvf4iehb0004356maa3lb17s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvf4iehb0005356mtgtri24o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvf4iehb0002356mirzf8yw5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvf4iehb0001356m5op9tjz0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvf4qeyz0002356mpbq0ghz7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvf4iehb0002356mirzf8yw5%2522%252C%2522activeTabId%2522%253A%2522clvf4qeyz0002356mpbq0ghz7%2522%257D%252C%2522clvf4iehb0005356mtgtri24o%2522%253A%257B%2522id%2522%253A%2522clvf4iehb0005356mtgtri24o%2522%252C%2522activeTabId%2522%253A%2522clvf4plg000l5356m0dsfw210%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522DOCS%2522%252C%2522id%2522%253A%2522clvf4o7d200hs356mq7xjk0tc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A8000%252C%2522id%2522%253A%2522clvf4plg000l5356m0dsfw210%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clvf4iehb0004356maa3lb17s%2522%253A%257B%2522id%2522%253A%2522clvf4iehb0004356maa3lb17s%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvf4iehb0003356mhvx78y3e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvf4iehb0003356mhvx78y3e%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Lezvix** [comment]
Just checked, "original" express  shows the same behaviour

**Comment by Lezvix** [comment]
And it seems isolated routers are a [long-standing](https://github.com/expressjs/express/issues/2760) [and unsolved](https://github.com/expressjs/express/issues/2828) [problem](https://github.com/pillarjs/router/issues/38)

**Comment by FullmetalBober** [comment]
Oh, i see, sorry for the distraction, my bad
