### ISSUE TITLE
hyper-express subdomains

### ISSUE THREAD

**Issue by pinqtape** [kartikk221/hyper-express#253]
Hi kartik, I'm sorry if my question seems stupid, but I'm interested to know a specialist like you about how I can better implement subdomains using your hyper-express library?

**Comment by kartikk221** [comment]
Hey, so subdomains are essentially DNS records which point to an IP address and hyper-express which can serve requests from a given IP address.

With that said, If you start hyper-express on a public port and create an A DNS record which points to the IP address on which hyper-express is serving requests, the subdomain will work.

If your use-case is web then the ports will be 80 for HTTP and 443 for HTTPS (With SSL).
