### ISSUE TITLE
Response._cork property is never reassigned

### ISSUE THREAD

**Issue by doxlik** [kartikk221/hyper-express#257]
Hello dear Kartik. First of all thank you for this perfect framework. I really like it and spent some time to investigate its source code and have a question. 

In the **Response** class we have following property 
```    /**
     * Whether this response needs to cork before sending.
     * @private
     */
    _cork = false;
```

and I found only two usages of it
**First**
```
    upgrade(context) {
        ...
        // Cork the response if it has not been corked yet for when this was handled asynchonously
        if (this._cork && !this._corked) {
            this._corked = true;
            return this.atomic(() => this.upgrade(context));
        }
       ...
```
**Second**
```
    send(body, close_connection) {
            ...
            if (this._cork && !this._corked) {
                this._corked = true;
                return this.atomic(() => this.send(body, close_connection));
            }
           ...
```

But I didn't find any place where you reassigned its value. I mean you initialize it with _false_ and then it never changes.
So my **question** is that why do we need this property that is always _false_? Did I just missed the place where it is reassigned or it is necessary for some future features?

I will be grateful for you answer.

**Comment by kartikk221** [comment]
The `Response._cork` property is assigned in the `Server.js` file after calling `Route.handle()` here https://github.com/kartikk221/hyper-express/blob/e98212ee8bb4273b6cf8c6b025d9c52e15cc9df0/src/components/Server.js#L530

The purpose of this property is to let the `Response` initiating method(s) know whether the `uWS.HttpResponse` needs to be corked or not as required by uWebsockets.js
