### ISSUE TITLE
file (sendFile) without caching

### ISSUE THREAD

**Issue by doxlik** [kartikk221/hyper-express#260]
As I see the implementation of the direct file sending (without streaming) is implemented in caching-only manner. I mean it is **not** optional to enable-disable caching of some particular files, while there are some cases when there is no need of caching (sending some very special file that most probably will be sent again in one month or never) and thus I want to ask, if you are able to add this possibility of disabling cache of the file or maybe you allow me to make a PR with this changes? I mean of course caching is important, but I think when we talk about framework (not about business code) the caching has to be optional, even if it is used in major cases.

**Comment by kartikk221** [comment]
Well the `Response.sendFile()` is an alias of `Response.file()` method and I can certainly look into making the caching optional though I don't see any mention of caching within the Express.js documentation for the sendFile() method.

Do you know of the exact function signature of the Express.js Response.sendFile() method and which option / property allows for controlling of caching?

**Comment by doxlik** [comment]
I am sorry for late response. I am a bit confused. You tell that you want to have compatibility with Express, but actually express has no caching at all. And also about memory, even loading file to the memory, does not make us to store it there then. If I am not mistaken express has options parameter, and while it generally does not have caching functionality, we can just add this option there, as extending options will not break compatibility. To be honest default caching actually break compatibility with Express, as it has no caching by default. At least I didn’t find anything in the docs. So, will it be too difficult to add this param to the options and them pass it to “file” method?

P.S. I am really grateful to you for this framework. I am no way criticise it, only want to suggest something useful.

**Comment by kartikk221** [comment]
I see what you mean. Yeah It seems extending the options to add an additional option is the best decision here. I'll work on adding an option to disable caching now. I will leave caching enabled by default to prevent this from being a breaking change.

**Comment by kartikk221** [comment]
Hey, after much thought, I believe any changes to the signature of the `Response.file()` method would be a breaking change or at least very inconvenient / odd to disable caching.

Since HyperExpress provides full flexibility for anyone to just pipe a stream or easily stream any local file using one of the many available methods / techniques such as `Response.stream()`, I think this issue can be closed for now.
