### ISSUE TITLE
Issue in setting an API gateway 

### ISSUE THREAD

**Issue by slabworwide** [kartikk221/hyper-express#262]
I am using http-proxy-middleware package to create  a API gateway. As per docs I implemented as below but it is not hitting the endpoint. Could you please tell how to fix.

```
import HyperExpress from 'hyper-express';
import { createProxyMiddleware } from 'http-proxy-middleware';

const webserver = new HyperExpress.Server();

webserver.use('/blog-service', (request, response) => {
  createProxyMiddleware({
        target: 'localhost:80',
        pathRewrite: {
            '^/blog-service':'/api/v1/blog/'
        },
      })
    
});


webserver.listen(81)
  .then((socket) => console.log('Webserver started on port 81'))
  .catch((error) => console.log('Failed to start webserver on port 81'));

**Comment by kartikk221** [comment]
Your example is very vague in that the problem lies within createProxyMiddleware utilizing some property or method of Express.js which is not fully compatible in HyperExpress.

I would either implement your own redirect middleware in HyperExpress or look at the source code createProxyMiddleware for clues.

**Comment by codealongwith** [comment]
Thanks For your reply. I understood the concept. I have another query , Could you please  tell me whether does hyper-express offer any in built logger library.

**Comment by slabworwide** [comment]
Thanks For your reply. I understood the concept, I would appreciate if you could provide a working example link of redirect middleware that hyper-express supports. However I am asking you for an example because I am bit confused as till now I have used reverse proxy method to built API gateways.
I have another query , Could you please tell me whether does hyper-express offer any in built logger library.

**Comment by abuu-u** [comment]
this is how i did it

```ts
import HyperExpress from 'hyper-express'
import { request } from 'node:http'

const server = new HyperExpress.Server()

server.any('/api/v1', (request_, response) => {
  request_.pipe(
    request(
      'http://localhost:8081/api/v1',
      {
        method: request_.method,
        headers: request_.headers,
      },

      (readable) => {
        readable.pipe(response)
      },
    ),
  )
})

const PORT = process.env['PORT'] ?? '3000'

await server.listen(PORT, () => {
  console.log(`Service endpoint = http://localhost:${PORT}`)
})
```
