### ISSUE TITLE
Important middleware (express-rate-limit) support needed. 

### ISSUE THREAD

**Issue by a4arpon** [kartikk221/hyper-express#263]
When I try to use express-rate-limit package with Hyper Express. It shows error. But this package is very important for day to day development. Please if you have time fix it. I am using your hyper express in my Production app. and its very great when it comes to handle hudge amount of traffic.

**Comment by kartikk221** [comment]
Hi, you would have to provide a reproducible example of the exact error. The exact incompatibility can only be discovered after that example.

**Comment by sudipzoom** [comment]
Express middleware is incompatible for sure. But we can create our own middleware considering fixed window method or token bucket method based on our application need. I have implemented it without any npm package.

**Comment by a4arpon** [comment]
> Express middleware is incompatible for sure. But we can create our own middleware considering fixed window method or token bucket method based on our application need. I have implemented it without any npm package.

Can you give me an example, brother. It'll be very helpful for me
