### ISSUE TITLE
How to enable cors in hyper-extress

### ISSUE THREAD

**Issue by sudipzoom** [kartikk221/hyper-express#264]
Hello Author ,

What is the correct method of enabling a cors in hyper-express.
I used  `response.setHeader('Access-Control-Allow-Origin', '*')` this in a PUT route handler, but once called this api  via fetch method using nextjs server actions, it work  but when called the same api from a client component it gives CORS error.                The application requires to execute this api from a client component only but I am getting a CORS error.

The CORS error occurs not only in nextjs but also any frontend application(React,Angular,Nextjs,Vuejs) when I called this api. But Nextjs executes this api only when the api is called with server actions. Only issues are seen with POST, PATCH,PUT api routes. GET api routes works fine with  `response.setHeader('Access-Control-Allow-Origin', '*')`.

Therefore, I think we need to use something like `webserver.use(cors())`, this works in express but not in hyper-express.
Nothing is mentioned in documentation. Looking forward for your reply.

Regards

**Comment by kartikk221** [comment]
My guess is that Next.js is not properly compatible with `hyper-express` as is and hence your PUT handler which is setting the header is not properly setting all of the neccessary headers for CORS.

You can either write your own middleware which writes all of the neccessary CORS headers or modify the fork of `express-cors` to properly use `hyper-express` to write the neccessary headers.

**Comment by codealongwith** [comment]
Thanks for your reply. Ok I am trying this an let you know .It seems **below way** middleware access to the router is not working in the current version 6.16.2 , But it was working in previous version. Now how can we access the middleware from the particular route handler. Please let me know it is not clear from updated docs.
```
export const corsMiddleware = async(request, response, next) => {
 response.header('vary', 'Origin')
        response.header('Access-Control-Allow-Headers', 'content-type')
        response.header('Access-Control-Allow-Methods', 'OPTIONS, POST, GET, PUT, DELETE')
        response.header('Access-Control-Allow-Origin', 'domain')
        response.header('Access-Control-Allow-Credentials', true)
    next();
}
```
```
api_v1_user_router.put('/profile-update',{
  middleware:[ corsMiddleware]
},async (request, response) => {
.....
}
```

**Comment by kartikk221** [comment]
For middlewares, you should use .use() not .put()

**Comment by codealongwith** [comment]
Hello, Thanks for helping me out. Still CORS middleware has issues
below is the middleware function
export const corsMiddleware = async(request, response, next) => {
        response.setHeader('vary', 'Origin')
        response.setHeader('Access-Control-Allow-Origin', '*')
        response.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization')
        response.setHeader("Content-Type", "application/json");
        response.setHeader('Access-Control-Allow-Methods', 'OPTIONS, POST, GET, PUT, DELETE')
        response.setHeader('Access-Control-Allow-Credentials', true)
    next();
}

I have implemented as below according to your advise-> 
auth middleware and other middlewares are working well. 

But cors middleware gives this error  `Text and data can only be passed by String, ArrayBuffer or TypedArray.` If I remove corsmiddleware , then api call works. 

Even I checked with putting same response headers inside the put route handlers and removed corsMiddleware , api call works.

Could you please check and tell me what went wrong!

`api_v1_user_router.use('/update', authMiddleware, corsMiddleware )`

```
api_v1_user_router.put('/update', async (request, response) => {
..................................
.................................

}
```

Looking for your reply. Thanks.

**Comment by sudipzoom** [comment]
Hello, Thanks for your reply.  Still CORS middleware has issues.
below is the middleware function

```
export const corsMiddleware = async(request, response, next) => {
        response.setHeader('vary', 'Origin')
        response.setHeader('Access-Control-Allow-Origin', '*')
        response.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization')
        response.setHeader("Content-Type", "application/json");
        response.setHeader('Access-Control-Allow-Methods', 'OPTIONS, POST, GET, PUT, DELETE')
        response.setHeader('Access-Control-Allow-Credentials', true)
    next();
}
```

I have implemented as below according to your advise->
results->
1. auth middleware and other middleware's are working well.

2. But cors middleware gives this error `Text and data can only be passed by String, ArrayBuffer or TypedArray`. If I remove corsmiddleware , then api call works.

Even I checked with putting same response headers inside the put route handlers and removed corsMiddleware , api call works.

Could you please check and tell me what went wrong!

`api_v1_user_router.use('/update', authMiddleware, corsMiddleware )`

```
api_v1_user_router.put('/update', async (request, response) => {
..................................
.................................

}
```
Looking for your reply. Thanks.

**Comment by kartikk221** [comment]
You are receiving that error because `response.setHeader('Access-Control-Allow-Credentials', true)` you can only set `string` values not booleans. Please ensure all of your header value arguments are strings.

**Comment by sudipzoom** [comment]
Its working now after I changed it to a string! Thank you so much for helping me out. 
I am putting my cors middleware code down below so that others might helped from this.
 **Please close this question**. Thank you for helping me out.

below middleware setting also working. Do we have to use use() one or below one.

api_v1_user_router.put('/update',{
  middlewares:[ corsMiddleware]
},async (request, response) => {
.....
}

Final Code:-
```
export const corsMiddleware = async(request, response, next) => {
        response.setHeader('vary', 'Origin')
        response.setHeader('Access-Control-Allow-Origin', '*')
        response.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization')
        response.setHeader("Content-Type", "application/json");
        response.setHeader('Access-Control-Allow-Methods', 'OPTIONS, POST, GET, PUT, DELETE')
        response.setHeader('Access-Control-Allow-Credentials', "true")
    next();
}
```

**Comment by sudipzoom** [comment]
I forgot to add one more issue, I am calling this api from frontend  server components or using server actions and thats why server does not need to get a clearance from browser and api call gets successful.

 If I call this api from a client component then chrome blocks the api call and giving a CORS error. It is not related to nextjs , reactjs . Its the browser which blocks the api  and gives CORS  error.  

I do not know what type of more headers to be set in the cors middleware function. I request author to provide a solution. Thank You.

**Comment by gaisdav** [comment]
Hi
I have an error with CORS. Is there any idea why I have it? :|

my code:

server.use(useCORS({ origin: '*', credentials: true }));

server.options(
  '/*',
  useCORS({
    origin: '*',
    credentials: true,
    optionsRoute: true,
  }),
);

repository with code: https://github.com/gaisdav/wishlist-server/blob/a0eb4d033e0b9e07e939e51df5b63dae1ae2b9fd/src/bootstrap.ts#L34

**Comment by timseriakov** [comment]
up

**Comment by nintra** [comment]
Setting headers like you did is correct. Additionally, you need to provide an "OPTIONS" method. So the browser can check what is allowed.
```js
webserver.options('*', (request, response) => {
    return response.send('')
})
```

**Comment by sqoodward** [comment]
Thanks for the help everyone. Wasted hours trying to figure out why my cookies aren't persisting after login til I found this.
