### ISSUE TITLE
Error: HyperExpress: Server/Router.use() -> Wildcard "*" & ":parameter" prefixed paths are not allowed when binding middlewares or routers using this method.

### ISSUE THREAD

**Issue by taylordwright44** [kartikk221/hyper-express#271]
Hello, I'm new to Hyper-Express and trying to rewrite my Express auth system in it. Right now I'm trying to forward my /posts/ route to be usable from the comments route so I can do something like post to `/api/posts/:id/comment` buy I'm getting the error that I can't use wildcards when binding to a middleware.

I'm doing it the same way I do in express as I couldn't seem to find documentation on how to do it in Hyper-Express, so it looks like this from my posts route:
`
const commentRouter = require('./comments');
const commentRouter = require('./comments');
`

My entire comments route looks like this:

`
const HyperExpress = require('hyper-express');
const { 
    getComments, 
    getComment, 
    addComment, 
    updateComment, 
    deleteComment
 } = require('../controllers/comments');

 const Comment = require('../models/Comment');

 const router = new HyperExpress.Router();

const advancedResults = require('../middleware/advancedResults');
//add protect ability; can now protect any route that needs to be logged in
const { protect, authorize } = require('../middleware/auth'); 

router.route('/')
.get(advancedResults(Comment, {
    path: 'post',
    select: 'name description'
}), getComments)
.post(protect, addComment);

router.route('/:id')
.get(getComment)
.put(protect, updateComment)
.delete(protect, deleteComment);

module.exports = router;
`

and the routes are mounted like so to the server.js

`
app.use('/api/posts', posts);
app.use('/api/comments', comments);
`

Is there a proper method for forwarding routes so I can use the same name scheme I used with Express?

**Comment by kartikk221** [comment]
Hello, yeah so the error you are running into is that HyperExpress fundamentally treats middlewares separately from routes.
See middlewares can only run on a certain route pattern and are "wildcard" by default.

For example:
```
server.use((req, res, next) => {}); // This will run for ALL requests since it has no pattern hence a global match
server.use('/api', (req, res, next) => {}); // This will run for `/api` and ALL `/api/*` requests since it narrows to `/api` pattern
```

Please keep in mind that HyperExpress is mostly compatible with Express.js with a very familiar API but it is not 100% compatible and the middleware system is currently one of the more major differences. Feel free to read up on our Middleware docs for more information on usage and behavior.
