### ISSUE TITLE
How to integrate with supertest

### ISSUE THREAD

**Issue by baszealot13** [kartikk221/hyper-express#279]
```
// server.spec.js
import request from 'supertest';
import server from '../src/server';

describe('loading express', () => {
  let server; // http server object

  beforeEach(async () => {
    delete require.cache[require.resolve('../src/server')];
    server = require('../src/server');
  });

  afterEach(() => {
    server.close();
  });

  it('responds to /', async () => {
    const response = await request(server).get('/');
    expect(response.status).toBe(200);
  });

  it('404 everything else', async () => {
    const response = await request(server).get('/foo/bar');
    expect(response.status).toBe(404);
  });
});

```

**Troubleshooting**
Error: TypeError: app.address is not a function:
This error typically occurs when the server is not properly closed after each test. Ensure that you are calling server.close() in your afterEach block.
Error: TypeError: server.close is not a function:
This error typically occurs when the server is not properly initialized. Ensure that you are correctly requiring and initializing your server in your test file.

**Comment by kartikk221** [comment]
Hi, HyperExpress shares limited compatibility with a familiar API to Express.js but not 100% compatible hence the errors you are seeing come from methods which have not been implemented on HyperExpress.

You would have to find their counter-parts in HyperExpress to make your test work.

**Comment by fawzy0z** [comment]
i have faced the same problem i wanted to use the SuperTest and i found solution by just test using url of your server

test
```
import request from 'supertest';

const test = request('http://localhost:4000');
describe('GET /', () => {
  it('should connect to backend server', async () => {
    const response = await test.get('/');
    expect(response.status).toBe(200);
  });
});
```


route 
```
app.get('/', (req, res) => {
  res.status(httpStatus.OK).send();
});
```

test pass ✅

![image](https://github.com/user-attachments/assets/0dfb6ba2-c442-4823-81fa-08576ff7758e)
