### ISSUE TITLE
method post body 

### ISSUE THREAD

**Issue by azkadev** [kartikk221/hyper-express#28]
the post method has a slight error in the req.json() section,

which sometimes can read the body sometimes not

I tried host api on heroku but in local work

here's the video issue

https://user-images.githubusercontent.com/82513502/144725211-b5d17ef6-9c19-4b97-aac4-486323e23d17.mp4

**Comment by kartikk221** [comment]
Try running the following code to parse the body:

let body;
try {
    body = await request.json(undefined);
} catch (error) {
    console.log(error);
}

The code above should log an error instead of defaulting to {} if there is a parsing error with the JSON.
