### ISSUE TITLE
This version of µWS is not compatible with your Node.js build  

### ISSUE THREAD

**Issue by RianAwan** [kartikk221/hyper-express#281]
throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
                Error: Cannot find module './uws_win32_x64_115.node'
                
I've tried NodeJS 18, 20 and 22 and none worked.
I've tried both in CommonJS and ESM both have this issue. I can't seem to find the source of problem.

**Comment by RianAwan** [comment]
And for reassurance, I've tried to import hyper express using require("hyper-express") function created by createRequire() function in ESM and had the same issue.

**Comment by kartikk221** [comment]
Could you run `node --version` and also provide which version of `hyper-express` are you running?

**Comment by RianAwan** [comment]
After a complete delete of ``node_modules`` and ``package-lock.json``, it seems to be working properly.

Though I am running ``v20.14.0`` and ``6.16.3`` HyperExpress.

Issue is fixed by reinstalling ``node_modules`` and ``package-lock.json``.
