### ISSUE TITLE
Is it possible to use hyper-express with Bun?

### ISSUE THREAD

**Issue by likecyber** [kartikk221/hyper-express#282]
hyper-express is one of my favorite Node.js package.

I've been using it in some of my Node.js projects for a while.
However, some projects can benefit a lot from switching from Node.js to Bun.
I would love to keep using this framework on Bun but I am faced with this error.

```
error: This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

TypeError: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
      at C:\...\node_modules\hyper-express\node_modules\uWebSockets.js\uws.js:22:9
      at C:\...\node_modules\hyper-express\node_modules\uWebSockets.js\uws.js:22:240
      at C:\...\node_modules\hyper-express\index.js:4:7

Bun v1.1.15 (Windows x64)
```

I know this error is from `uWebSockets.js` module not `hyper-express` itself.

but is it possible to have `hyper-express` working with Bun?

I would love Node.js and Bun to be able to run the same server script.

**Comment by kartikk221** [comment]
Hello, since `hyper-express` is built on top of `uWebsockets.js` there will be no way to make it work on Bun without Bun also supporting `uWebsockets.js`.

As the error states, this is a napi error which Node's API for communication / working with C++ modules like uWebsockets.
