### ISSUE TITLE
Http version 1.0 not supported

### ISSUE THREAD

**Issue by ascenttree** [kartikk221/hyper-express#287]
I tried to migrate my project from express to hyper-express (because express sucks at body reading) and now im getting an error "Http version 1.0 is not supported uWebSockets/20 server"

**Comment by kartikk221** [comment]
uWebsockets.js, the underlying library used by HyperExpress, does not support the Http 1.0 protocol. I believe only Http 1.1 and up is supported hence you will have to send your request over a supported protocol version.

**Comment by ascenttree** [comment]
im requesting through a web browser though? shouldn't that be 1.1
