### ISSUE TITLE
Issue in configure a multer middleware.

### ISSUE THREAD

**Issue by slabworwide** [kartikk221/hyper-express#293]
Hello Author,   
I need to use multer package in this application.  below is my code:-                                                                                                                                                                                                    

```
const upload = multer({ dest: 'uploads/' })


upload_router.use('/file-uploads', upload )
upload_router.post('/file-uploads', async (request, response) => {
const file = request.file.path

console.log('file') // undefined

response.send("ok")
})
```

I am uploading a file via http request body(form-data) using postman with a 'file' key. but getting file as undefined in the console after the upload. Please help me to find what went wrong.

**Comment by kartikk221** [comment]
Hi, this could potentially mean that the multer package is not compatible with HyperExpress out of the box.

Have you tried using the built-in multipart file uploading within HyperExpress?

**Comment by slabworwide** [comment]
Thanks for your reply.  built-in multipart file is working out of the box. But in documentation it is not clear that how can we enhance  file handling limitation.I am going to handle heavy files of minimum size 5gb. However in multer we can define maximum file size  to be handled                                                                                                                                                                       ```
const upload = multer({
  storage: storage,
  limits: { fileSize: maxSize /* bytes */ }
})                                                                                                                                                                                                                                       
```                                                                                                                                                                                                                     Can we handle it like below? what is your opinion?                                                  ```
const fileSize = parseInt(request.headers["content-length"])

    if ((file.mimetype === "image/png" || file.mimetype === "image/jpg" || file.mimetype === "image/jpeg" || file.mimetype === "application/octet-stream") && fileSize <= 10737418240) {
        cb(null, true)
    } else if (file.mimetype === "video/mp4" && fileSize <= 21474836480) {
        cb(null, true)
    } else {
        cb(null, false)
    }
```

**Comment by slabworwide** [comment]
Thanks for your reply.  built-in multipart file is working out of the box. But in documentation it is not clear that how can we enhance  file handling limitation.I am going to handle heavy files of minimum size 5gb. However in multer we can define maximum file size  to be handled                                                                                                                                                                
                                                                                                                                                                      
```
const upload = multer({
  storage: storage,
  limits: { fileSize: maxSize /* bytes */ }
})    
```                                                                                                                                                                                                                                                                                                                                                                                                                          Can we handle it like below? what is your opinion?       
                                       
```
const fileSize = parseInt(request.headers["content-length"])

    if ((file.mimetype === "image/png" || file.mimetype === "image/jpg" || file.mimetype === "image/jpeg" || file.mimetype === "application/octet-stream") && fileSize <= 10737418240) {
        cb(null, true)
    } else if (file.mimetype === "video/mp4" && fileSize <= 21474836480) {
        cb(null, true)
    } else {
        cb(null, false)
    }
```

**Comment by slabworwide** [comment]
Thanks for your reply.  built-in multipart file is working well for normal cases. But multipart does not work well during heavy lifing of files,I think may be we need to define file size in bytes for big files. I am going to handle big files(minimum size 5gb). However in multer we can define maximum file size  to be handled and multer works well with big files. Can we handle multipart like below? what is your opinion?                                                                                                                                                                    
    ```
const fileSize = parseInt(request.headers["content-length"])

    if ((file.mimetype === "image/png" || file.mimetype === "image/jpg" || file.mimetype === "image/jpeg" || file.mimetype === "application/octet-stream") && fileSize <= 10737418240) {
        cb(null, true)
    } else if (file.mimetype === "video/mp4" && fileSize <= 21474836480) {
        cb(null, true)
    } else {
        cb(null, false)
    }
```
