### ISSUE TITLE
Does hyper-express support or will support the addChildAppDescriptor from /examples/WorkerThreads.js

### ISSUE THREAD

**Issue by BolverBlitz** [kartikk221/hyper-express#297]
Is it already possible to replicate what the /examples/WorkerThreads.js from uWebSockets.js does with hyper-express?

**Comment by kartikk221** [comment]
Hey, there currently isn't a defined method for that use case. However, you can simply access the underlying uWS.TemplatedApp instance by using the Server.uws_instance property.
