### ISSUE TITLE
Websocket only returns type string

### ISSUE THREAD

**Issue by ArthurTimmermans** [kartikk221/hyper-express#299]
Hello everyone,

I have created a web socket on hyper-express (version 6.17.2) and have the issue that messages are always recognised as type 'string' while I send for example Binary data.
![CleanShot 2024-09-20 at 16 50 11](https://github.com/user-attachments/assets/d37722ab-2ec4-482d-a6e4-db5dffdb07fc)

**Is this a known issue or something related to my code?**

**Message send via Postman:**
![CleanShot 2024-09-20 at 16 39 37@2x](https://github.com/user-attachments/assets/de25490e-fa44-4e0f-ad31-4172f5b978cf)

**Backend Code**
```const HyperExpress = require('hyper-express');
const webserver = new HyperExpress.Server();

webserver.get('/', (request, response) => {
    response.status(200).send("Hello world");
})

// WebSocket route 
webserver.ws('/stream', {max_payload_length: 5 * 1024 * 1024 }, (ws) => {
    console.log('Socket connection opened.');

    ws.on('message', (message) => {
        console.log('Type of message:', typeof message); //Gives type of message
        if (Buffer.isBuffer(message)) {
            // This will check if the data is binary (received as Buffer in Node.js)
            console.log('Received binary data (Buffer):');
        } else {
            console.log('Received non-binary data:');
        }
    });
    ws.on('close', (code, reason) => {
        console.log(`WebSocket connection closed. Code: ${code}, Reason: ${reason}`);
    });
});
webserver.listen(6060)
    .then((socket) => console.log("Webserver started on port 6060"))
    .catch((error) => console.log("Failed to start webserver on port 6060"))````

**Comment by kartikk221** [comment]
Hi, please review the docs for Router and you will find that when binding Router.ws() to create a route, you can specify a message_type option alongside other route options which will dictate the type of the data.

So essentially you can change the default string parsing behavior by defining the message_type option alongside max payload length and others.
