### ISSUE TITLE
ERR_INVALID_CHUNK_ENCODING when piping a huge stream

### ISSUE THREAD

**Issue by SupertigerDev** [kartikk221/hyper-express#304]
When piping a large image, the image does not fully get sent.
![image](https://github.com/user-attachments/assets/f641a228-ff1f-4bcb-a508-36f7433cb38f)

Windows 11 64 bit
node v20.16.0
hyper-express 6.17.2

Edit: This seems to be working perfectly fine on Ubuntu under WSL

Reproduction: 
1. Clone https://github.com/SupertigerDev/hyper-express-pipe-bug
2. `npm i`
3. `node .`

An express server should be started on https://localhost:3000 and hyper-express server should be started on https://localhost:3001

Go to the first port, see that it works perfectly on express.
Go to the second port, see that the image only partially loads.

```ts
const { Server } = require("hyper-express");
const fs = require("fs");

const app = new Server({});

app.get("/", (req, res) => {
  const readable = fs.createReadStream("./image.jpg");

  readable.pipe(res);
});

app.listen(3001, () =>
  console.log("HyperExpress running on http://localhost:3001")
);
```

**Comment by reynaldichernando** [comment]
I wasn't able to reproduce this on macOS also, the image loads fine.

Anyway, this code also works for streaming a Readable in hyper-express, maybe worth a try.
`res.stream(readable);`

**Comment by SupertigerDev** [comment]
Exactly the same behaviour on windows. seems like its a windows only issue indeed.
![{694BDC25-6F93-46FE-8E36-A89B555D0344}](https://github.com/user-attachments/assets/1219989b-5779-46df-a582-74f093707852)

**Comment by kartikk221** [comment]
Hello, are you able to create a reproducible JS script for this behavior or are you only able to recreate this in the browser?
