### ISSUE TITLE
res.set(object) fails

### ISSUE THREAD

**Issue by kapouer** [kartikk221/hyper-express#307]
The error is easy to fix:
https://github.com/kartikk221/hyper-express/blob/e5fd1211df4bc89fbb05b342e795fb30cd2d5eb6/src/components/compatibility/ExpressResponse.js#L95

should be 
`reference.header(name, value);`

**Comment by kartikk221** [comment]
Good catch! Would you like to make a PR or should I push a commit to resolve this bug?

**Comment by reynaldichernando** [comment]
I would like to work on this 🙏
