### ISSUE TITLE
res.sendStatus is supposed to call end()

### ISSUE THREAD

**Issue by kapouer** [kartikk221/hyper-express#309]
To keep express compatibility, res.sendStatus() should call end():
https://expressjs.com/en/4x/api.html#res.sendStatus

**Comment by kartikk221** [comment]
Good catch! Would you like to make a PR for this fix or do you want me to push a commit?

**Comment by kapouer** [comment]
I'm okay with no PR - I'm busy trying to port a quite big project to hyper-express.
