### ISSUE TITLE
[feature] Express.js Middleware Wrapper

### ISSUE THREAD

**Issue by OpenReplicant** [kartikk221/hyper-express#321]
I just decided to hack together a middleware wrapper (with the help of Claude Sonnet via a test-driven development method, and the docs provided) to make use of potentially any Express.js middleware in Hyperexpress. I learned quite a bit about the differences between the two servers and the request object, and this iteration passed all the tests that had failed to use middleware correctly, still I'd love it if anyone in the know could look it over or test it themselves.

https://github.com/OpenReplicant/Hyperexpress-MiddleWrap

**Comment by kartikk221** [comment]
Hey! This look like a really cool project. I really appreciate you trying to tackle this challenge. Unfortunately, there are some low level differences between Express.j / Hyper Express / uWebsockets.js that make 100% compatibility a bit difficult without a core re-write but a wrapper should certainly be able to resolve a lot of the surface level incompatibilities like setters / getters / properties.
