### ISSUE TITLE
Can you publish the new version in NPM, please?

### ISSUE THREAD

**Issue by sshrshnv** [kartikk221/hyper-express#326]
More than 20 commits since the last NPM version.

**Comment by ezioda004** [comment]
@kartikk221 can you please? Waiting for node 23 support

**Comment by sshrshnv** [comment]
Eventually I found a kept up to date variant:
https://github.com/dimdenGD/ultimate-express

**Comment by kartikk221** [comment]
> @kartikk221 can you please? Waiting for node 23 support

Sorry this took too long. Was extremely busy last few weeks. This has been pushed in the recent `v6.17.3` update.
