### ISSUE TITLE
VSC Debuger

### ISSUE THREAD

**Issue by CQZW** [kartikk221/hyper-express#330]
After I started the server through hyper-express, VSC could not debug by attaching to Node Process. The first attempt was unresponsive, and the second attempt prompted an error: 'user-defined signal 1';
If I had not executed the hyper-express code, I could attach normally

**Comment by kartikk221** [comment]
This may have something to do with `hyper-express` being based on a lower level C++ Node Addon called `uWebsockets.js`.

Unfortunately, we cannot add support for this easily as `hyper-express` does not contain nor directly modify any native code.
