### ISSUE TITLE
unresolved package.json conflicts

### ISSUE THREAD

**Issue by leeoniya** [kartikk221/hyper-express#38]
@kartikk221 

https://github.com/kartikk221/hyper-express/blob/d92ed8fa9f8a1f32364cf80b78980800a2b772d7/tests/package.json#L12-L17
https://github.com/kartikk221/hyper-express/blob/d92ed8fa9f8a1f32364cf80b78980800a2b772d7/tests/package-lock.json#L12-L17

**Comment by kartikk221** [comment]
Looks like these were caused by a snyk merge, I have pushed a commit to resolve this. Thanks for the heads up!
