### ISSUE TITLE
Publish Sub

### ISSUE THREAD

**Issue by jeffery30162** [kartikk221/hyper-express#50]
I have subscribed a ws to a topic but the publish method doesn't exist on the server object. 
The publish method exists within the websocket.js object.

**Comment by jeffery30162** [comment]
Adding this to your Server.js resolves the issue:
`	/**
     * Publish a message to a topic in MQTT syntax.
     * You cannot publish using wildcards, only fully specified topics.
     *
     * @param {String} topic
     * @param {String|Buffer|ArrayBuffer} message
     * @param {Boolean=} is_binary
     * @param {Boolean=} compress
     */
    publish(topic, message, is_binary, compress) {
        if (this.#uws_instance) return this.#uws_instance.publish(topic, message, is_binary, compress);
        return false;
    }`

**Comment by kartikk221** [comment]
Yes, that is per-spec from how uWebSockets.js implements Pub/Sub with its web sockets. You can only publish a message from a Websocket object. See the uWebsockets.js documentation if you would like to discover more regarding why this was implemented in HyperExpress in this way.

**Comment by kartikk221** [comment]
> Adding this to your Server.js resolves the issue: ` /** * Publish a message to a topic in MQTT syntax. * You cannot publish using wildcards, only fully specified topics. * * @param {String} topic * @param {String|Buffer|ArrayBuffer} message * @param {Boolean=} is_binary * @param {Boolean=} compress */ publish(topic, message, is_binary, compress) { if (this.#uws_instance) return this.#uws_instance.publish(topic, message, is_binary, compress); return false; }`

I see, thanks for bringing this up. It seems the TemplatedApp.publish() method was implemented in updates after the original modules of Websocket/Server were written for HyperExpress.

Server.publish() has been implemented in v5.7.0. You may upgrade to use this method going forward.

**Comment by jeffery30162** [comment]
Thanks
I tried cloning the master branch, was going to add code and try to commit but seems I am unauthorized.
