### ISSUE TITLE
Do you have the scalable hyper-express server and client example?

### ISSUE THREAD

**Issue by ksarpotdar** [kartikk221/hyper-express#51]
Hi Karthik,

First of all, I haven't tried hyper-express or even uWebsockets. I normally use socket.io along with PM2 and Redis if scalable architecture needed. I liked your efforts and develop a hypre-express. I appreciate this middleware application and also that its on top of uWebsockets.js, which is high performance. I would like to know if there is a scalable example of server and client, say for the clients sending many messages and file streaming say about 100Mb (take any size).
1. It should allow the normal GET POST requests
2. It should allow creating two sockets one for normal message and another for file sharing in same client, with login check (point 5)
3. Ensuring that all cores are used and scalable if I install another machine, say like socket-io/pm2 and Redis adapters.
4. CORS requests configuration
5. session / cookie / any other way, with authentication like passport.js (standard email password use case, with email to new registration, validation of it, login and logout, along with session)
6. data from Redis and Sqlite database (based on whether the normal DB or in-memory DB is needed 
7. the routing needed, obviously for GET POST requests

Nothing fancy needed, just

Can you help with that? I tried to check your contact details like email id but couldn't get it, so logging as an issue.

Keep up the great work! I am following you to check the updates.

You can delete this request and update your id, if you wish to connect.

**Comment by kartikk221** [comment]
Hi, so HyperExpress is meant to be very developer friendly and familiar to Node.js developers who have worked with Express.js in the past. I currently don't have an official example template repository for building such application but I would recommend you build out the application you proposed above the same way you would with just Express.js

In fact, HyperExpress is practically drop-in compatible for Express.js projects as HyperExpress implements the same properties/methods/patterns as Express for its functionality. So this means any existing codebases, templates, middlewares and packages should be compatible to be used with HyperExpress.

**Comment by ksarpotdar** [comment]
Thank you very much Karthik! Appreciate the response.
