### ISSUE TITLE
Topic Publish Example with Hyper-Express

### ISSUE THREAD

**Issue by half-metal** [kartikk221/hyper-express#54]
Hi, glad to get this working, but ran into an issue with the ws.publish, do you have an example to show a publish working as expected for this: 
`publish(String: topic, String|Buffer|ArrayBuffer: message, Boolean: is_binary, Boolean: compress): Publishes the specified message to the specified topic in MQTT syntax.`
This is the gist of what I tried using below:
```
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const HyperExpress = require('hyper-express');
const Server = new HyperExpress.Server();
const Router = new HyperExpress.Router();
Server.listen(8082)
Server.ws('/', (ws) => {

    ws.id = randomUUID()
    ws.subscribe = uTopic
    connections[ws.id] = ws
    connections[ws.id].publish('locationHb', 'you are now subscribed to locationHb') // not sent to client
    ws.publish('locationHb', 'you are now subscribed to LocationHb') // not sent to client
    connections[ws.id].send('Client ID is' + ws.id) //sent to client
    console.log('Number of clients Object.keys(connections).length;', Object.keys(connections).length)
    clientCount = Object.keys(connections).length

    console.log('Client ID is:' + ws.id)
        ws.on('close', () => {
        console.log('Client ID disconnected:' + ws.id)
        delete connections[ws.id];
        })
}
```

This page discusses using MQTT which is good, but not seeing a clear example https://github.com/kartikk221/hyper-express/blob/master/docs/Websocket.md

I see they are subscribed, but still not receiving messages
![image](https://user-images.githubusercontent.com/58837299/154780433-ffdab440-391b-42d0-a264-0ee8e634281a.png)

Thanks

### Discussed in https://github.com/kartikk221/hyper-express/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **debshaw13** December 13, 2021</sup>
Does hyper-express have an equivalent function to broadcast (that is available in ws)? For example, using ws, the following code broadcasts data without any connections:

```
const wss = new WebSocket.Server({ port: 8082 });

wss.broadcast = (data) => {
  wss.clients.forEach((client) => {
    client.send(data);
  });
};
```

If I replace 'WebSocket' above with 'HyperExpress' (after importing 'hyper-express' of course), I see the following error: 

> TypeError: Cannot read property 'forEach' of undefined

Would appreciate any advice as to what I am doing wrong. Thank you for the great package, and apologies if this is a newbie question. 

</div>

**Comment by kartikk221** [comment]
Hi, so MQTT is essentially a URL protocol which determines how Publish/Subscribing will work between multiple parties.

The reason why your example is not working is because connections must first subscribe to a topic using the `Websocket.subscribe(topic)` method.

Then whenever you want to publish a message to all connections on a `Server` instance, you can simply do `Server.publish(topic, message)` to broadcast a message.

Below is a simple example of this:
```javascript
const crypto = require('crypto');
const HyperExpress = require('hyper-express');
const Server = new HyperExpress.Server();

// Create an endpoint for accepting websocket connections
Server.ws('/connect', (ws) => {
    // Attach a unique identifier to each connection
    ws.id = crypto.randomUUID();
    
    // Subscribe the connection to "OUR_TOPIC_NAME"
    ws.subscribe('OUR_TOPIC_NAME');
    console.log(`Websocket Connection ${ws.id} Is Now Connected & Subscribed To OUR_TOPIC_NAME!`);
    
    // Bind any handlers here for this connection, we will bind the close handler so we can log closure
    ws.on('close', (code, message) => {
        console.log(`Websocket Connection ${ws.id} Has Disconnected!`);
    });
});

// Now you can publish a message to all connections over the "OUR_TOPIC_NAME" topic like below
Server.publish('OUR_TOPIC_NAME', 'This is a message for OUR_TOPIC_NAME subscribers!');
```

I'll also be adding an example for MQTT Pub/Sub in the Examples section of the documentation in the next update.

Hope this helps!

**Comment by half-metal** [comment]
awesome, that works, I appreciate the example. Yes, I needed to have ws.subscribe('topic') instead of ws.subscribe = 'topic' and as you showed there Server.publish - Thank you!
