### ISSUE TITLE
Typescript Types

### ISSUE THREAD

**Issue by SupremeTechnopriest** [kartikk221/hyper-express#64]
Hello! 

Im currently evaluating hyper-express vs nanoexpress.  Nanoexpress has some typescript type issues (its written in javascript and provides a d.ts with a bunch of errors).  With HyperExpress I cant seem to import any types.  For example, trying to write a middleware:

```ts
const middleware = (req: ?, res: ?, next: ?) => {
   return next()
}
```

Are these types exported anywhere?

Thank you

**Comment by kartikk221** [comment]
HyperExpress is also written in Javascript and implements its types through the d.ts files contained in /types folder.
I would assume you should be able to import types just like you would import components in TypeScript/Module system of Node.
For the specific use case above, you should look at 
https://github.com/kartikk221/hyper-express/blob/master/types/components/router/Router.d.ts
to find any specific exported types you may need for your purpose.

**Comment by SupremeTechnopriest** [comment]
Thanks for the reply @kartikk221!

I think the problem is that `Request`, `Response` etc is not exported in the types.  Seems like only `Server` and `Router` are exported.

I think adding changing `index.d.ts` to:

```ts
export * as compressors from 'uWebSockets.js';
export Server from './components/Server';
export Router from './components/router/Router';
export Request from './components/http/Request';
export Response from './components/http/Response';
```

would be a good start.

Also, if you can export these two types https://github.com/kartikk221/hyper-express/blob/master/types/components/router/Router.d.ts#L7-L8 I should be able to import them. 

Would you like a pull request?

**Comment by kartikk221** [comment]
Oh I see, yeah go ahead and make a pull request and I'll merge it.
Currently working on the 6.0.0 update which would include API improvements, type improvements and support for Node 18 / uWebsockets.js 20.8.0, so will get this published right along with that.

**Comment by SupremeTechnopriest** [comment]
Sounds good!  I will do that now.  Any idea when 6.0.0 is going to be released?  Anything I can do to help?

**Comment by kartikk221** [comment]
It's almost done, just writing/updating tests, types and docs for the few changes that have been made. 
Should be released later today hence the timing will line up to have your pull request included.
My only request would be to export essentially any and all types you think may be useful/referenced by users but I think the Server, Router, Request and Response exports you have above are already good ones to start with.

**Comment by SupremeTechnopriest** [comment]
Can do!

**Comment by SupremeTechnopriest** [comment]
#65 opened.

**Comment by SupremeTechnopriest** [comment]
Hows the release looking, think its going to get published tonight or should I just link my fork for now?

**Comment by kartikk221** [comment]
Hey, I'm essentially done with the update and just need to do a quick skim tomorrow morning before I publish the update. 6.0.0 will 100% be released tomorrow, so If your current use case is more tim sensitive, feel free to fork/link your current modifications.

**Comment by SupremeTechnopriest** [comment]
Will do, I will probably have a few more pushes to my PR as I run through and test it all out.  Will talk tomorrow!

**Comment by SupremeTechnopriest** [comment]
Do you mind if I add a setter for `req.body`?  I need to write my own body parser middleware.  Or would you prefer to expose `req._body` in the typedefs?

**Comment by kartikk221** [comment]
Do a setter for Request.body which writes the value to the underlying _body property.

**Comment by SupremeTechnopriest** [comment]
Will do.

**Comment by SupremeTechnopriest** [comment]
Let me know when this gets published.  So far so good on my side.

**Comment by kartikk221** [comment]
> Let me know when this gets published. So far so good on my side.

6.0.0 should be published. Let me know If you find any problems with documentation or types. I had to modify the JSDoc types a little bit to make the intellisense work properly for Non-Typescript projects.

**Comment by SupremeTechnopriest** [comment]
Awesome.  Installing now and will let you know if I run into anything.
