### ISSUE TITLE
Static files server

### ISSUE THREAD

**Issue by antn9x** [kartikk221/hyper-express#71]
How can I serve static files like "express.static"?

**Comment by kartikk221** [comment]
Hello, so you have a few options when it comes to this.
- Use Express's built-in `express.static()` middleware as it should be compatible with HyperExpress.
- See [LiveDirectory](https://github.com/kartikk221/hyper-express/blob/master/docs/LiveDirectory.md) for static/file asset serving.
- Roll out your own lightweight solution where you map the incoming url path to the local system path securely and stream the file

Hope the above helps, I plan on rolling out a few middlewares native to HyperExpress for basic things like Express-Like body parsing and static asset serving as well in the future.
