### ISSUE TITLE
Cannot use hyper-express middleware with express-graphql.

### ISSUE THREAD

**Issue by francelwebdev** [kartikk221/hyper-express#76]
Hello, I just tried https://github.com/graphql/express-graphql with https://github.com/kartikk221/hyper-express and it didn't work at all. I tried using as middleware and it didn't work at all and when I tried with get and post it worked.

**Comment by kartikk221** [comment]
Could you provide more information on what specific errors or functionality did not work with the middleware? Were there any errors logged to console or did the middleware simply not execute?

**Comment by dougg0k** [comment]
I recommend you looking into this one https://benzene.vercel.app/, it is the fastest option available and works very well with `hyper-express`, I have an API running with them both. 

https://benzene.vercel.app/benchmarks

**Comment by francelwebdev** [comment]
ok it support file upload ?

**Comment by dougg0k** [comment]
Not sure, but you can probably adapt since the core beneze are very minimal and compatible with many different servers clients.
