### ISSUE TITLE
About benchmarks and lists

### ISSUE THREAD

**Issue by h2atecnologia** [kartikk221/hyper-express#81]
First of all, I want to show my humility and respect for the beautiful work you have done.
but i need to ask. 

why the absence of hyper-express or even WebSockets in the techempower benchmarks list [link](https://www.techempower.com/benchmarks/)

after all, 8.5x more than fastify would guarantee us an excellent position on this list.

**Comment by kartikk221** [comment]
Hey, to be completely honest, I'm not really sure how to get HyperExpress added as an option on TechEmpower as their UI seems very confusing. If you could point me to a specific contact, I would be more than glad to reach out so they can evaluate and add HyperExpress. 

Also, there is another problem with HyperExpress showing significantly lower results when benchmarked locally over localhost vs. over network (similar to real world scenarios) where benchmarking locally leads to Node's internal queueing/event loops being the bottleneck for the throughput of requests. For this reason, network benchmarks are much more accurate for HyperExpress but many benchmarking platforms simply benchmark locally hence you may see differences. I did recently have HyperExpress added to https://web-frameworks-benchmark.netlify.app/result where you can see this behavior.

**Comment by h2atecnologia** [comment]
Thank you for your quick response and especially for your comments.
I went to look at the site you passed and noticed that we are on it at 0.25% ahead of polkadot. doing a simple and perhaps wrong math, we would also be ahead of polkadot on the techempower list and thus being around position 120 on the Fortunes list (Fastify is at 199). I'm going to take a look at how we can participate in the techempower benchmarks and get back to talking.
Once again, congratulations for the excellent work.
