### ISSUE TITLE
Q: How to set custom fields for request

### ISSUE THREAD

**Issue by afrokick** [kartikk221/hyper-express#82]
Hey! @kartikk221 could you please suggest how to assign some field to a request object and fix types issue.

There are a lot of middleware which can extend request object for some reasons.

For example I want to set a custom field `uid`:

```
apiRouter.get('/test', (req, res) => {
  req.uid = 'test_uid'; // <- How to extend HyperExpress.Request type to support it?
});
```

Is it a properly way?

**Comment by kartikk221** [comment]
Hi @afrokick the plan for future updates is to implement the same types structure as Fastify/Express as theirs is well written for expansion purposes to the Request/Response components.

At the moment, to have type safety for your properties added onto the `Request`/`Response` components, you would have to create your own type interface and then provide that as the type for the components as shown below.
```ts
import { type Request, type Response } from 'hyper-express';

interface ApiRouterRequestProps {
    uid?: string
}

interface ApiRouterResponseProps {
    uid?: string,
    ts?: number
}

apiRouter.get('/test', (req: Request<ApiRouterRequestProps>, res: Response<ApiRouterResponseProps>) => {
    // We can now optionally add the uid property to Request as speciified in ApiRouterRequestProps
    req.uid = 'something';
    
    // We can now optionally add the uid property to Request as speciified in ApiRouterResponseProps
    res.uid = 'something else';
    res.ts = Date.now();
});
```
