### ISSUE TITLE
Submit to https://github.com/fastify/benchmarks

### ISSUE THREAD

**Issue by kurtextrem** [kartikk221/hyper-express#94]
Hi,

the benchmarks in the README are impressive, maybe it would be worth to submit hyper-express to the fastify benchmark repo? https://github.com/fastify/benchmarks

**Comment by kartikk221** [comment]
Yep, as @BobbyWibowo mentioned above, I almost always try to only submit hyper-express to benchmarks that aren't strictly restricted to Node.js HTTP module based solutions as uWebsockets.js will have a clear upper hand in just pure throughput. While one can make the case that the developer experience/API from a webserver is really the only thing that should matter for being benchmark candidates, this would just lead to arugmentative discussions in said PRs/Issues.
